### ISSUE TITLE
keadm: debian 10 unsupported

### ISSUE THREAD

**Issue by hacker-h** [kubeedge/kubeedge#1246]
keadm does not support debian 10:
```
# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@debian1:/home/debian1/keadm-v1.1.0-linux-amd64/keadm# ./keadm init
panic: This OS version is currently un-supported by keadm

goroutine 1 [running]:
github.com/kubeedge/kubeedge/keadm/app/cmd/util.GetOSInterface(...)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/app/cmd/util/common.go:189
github.com/kubeedge/kubeedge/keadm/app/cmd/util.(*K8SInstTool).InstallTools(0xc00009ecc0, 0xc000129740, 0xc0000c9c60)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/app/cmd/util/k8sinstaller.go:37 +0x501
github.com/kubeedge/kubeedge/keadm/app/cmd/cloud.Execute(0xc000129740, 0xc000129770, 0xc00009ea80)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/app/cmd/cloud/init.go:166 +0xbd
github.com/kubeedge/kubeedge/keadm/app/cmd/cloud.NewCloudInit.func1(0xc000107180, 0x124c980, 0x0, 0x0, 0x0, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/app/cmd/cloud/init.go:70 +0xab
github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra.(*Command).execute(0xc000107180, 0x124c980, 0x0, 0x0, 0xc000107180, 0x124c980)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:826 +0x465
github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000106f00, 0xc00009c000, 0xcd4860, 0xc00009c008)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:864
github.com/kubeedge/kubeedge/keadm/app.Run(0x22, 0xc0000d4bd0)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/app/keadm.go:34 +0xcc
main.main()
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/keadm.go:27 +0x26
```

**Comment by rzr** [comment]
I managed to build a deb package for debian 10

Ping me if you want to test my patches  or  try package at:
https://dl.bintray.com/rzr/deb/pool/k/kubeedge/

**Comment by rzr** [comment]
ok I might reconsider to try it
once my pending changes are merged:

https://github.com/kubeedge/kubeedge/pulls/rzr

**Comment by fisherxu** [comment]
@rzr  Do we need reopen it?

**Comment by rzr** [comment]
Let's ask @hacker-h 

Meanwhile I can try to refresh my patches.
