### ISSUE TITLE
When try to deploy the modbus mapper, the modbus container failed

### ISSUE THREAD

**Issue by markwangC** [kubeedge/kubeedge#1316]
When try to deploy the modbus mapper, the container failed with below info.

root@edge-node:~/cmd# docker logs -f 4b6
CONNECTOR_DPL_NAME=dpl/deviceProfile.json
CONNECTOR_MQTT_IP=127.0.0.1
CONNECTOR_MQTT_PORT=1883
[2019-12-13T00:51:55.096] [INFO] appenders - start to watch dpl config
[2019-12-13T00:51:55.104] [INFO] appenders - start to check devicetwin state
[2019-12-13T00:51:55.169] [INFO] appenders - start to wait for devicetwin update
[2019-12-13T00:51:55.175] [INFO] appenders - connetced to edge mqtt with topic twinGet
[2019-12-13T00:51:55.179] [INFO] appenders - connetced to edge mqtt with topic twinDelta
[2019-12-13T00:51:55.216] [INFO] appenders - recieve twinGet msg, set properties actual value map
[2019-12-13T00:51:57.108] [INFO] appenders - chechking devicetwin state
/opt/src/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/opt/src/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/src/node_modules/@serialport/bindings/lib/linux.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

root@edge-node:/opt/go/src/github.com/kubeedge/kubeedge/mappers/modbus_mapper# node -v
v12.13.1
root@edge-node:/opt/go/src/github.com/kubeedge/kubeedge/mappers/modbus_mapper# npm -v
6.13.4

**Comment by markwangC** [comment]
it may related to my env, i think we can close this issue.
