### ISSUE TITLE
edgecore run failed on armv7l

### ISSUE THREAD

**Issue by latelee** [kubeedge/kubeedge#1360]
**What happened**:
I try to run edgecore on armv7l target board,but it failed. Some information is here:
```
I1231 17:01:33.207696     625 docker_service.go:271] Setting cgroupDriver to systemd
I1231 17:01:33.215316     625 edged.go:544] RemoteRuntimeEndpoint: "unix:///var/run/dockershim.sock", remoteImageEndpoint: "unix:///var/run/dockershim.sock"
I1231 17:01:33.219005     625 edged.go:547] Starting the GRPC server for the docker CRI shim.
I1231 17:01:33.258673     625 state_mem.go:36] [cpumanager] initializing new in-memory state store
I1231 17:01:33.285675     625 state_mem.go:84] [cpumanager] updated default cpuset: ""
I1231 17:01:33.288103     625 state_mem.go:92] [cpumanager] updated cpuset assignments: "map[]"
I1231 17:01:33.318170     625 kuberuntime_manager.go:205] Container runtime docker initialized, version: 17.05.0-ce, apiVersion: 1.29.0
I1231 17:01:33.445529     625 container_manager_linux.go:275] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName:systemd KubeletCgroupsName:systemd ContainerRuntime:docker CgroupsPerQOS:false CgroupRoot: CgroupDriver:systemd KubeletRootDir:/var/lib/edged ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy: ExperimentalCPUManagerReconcilePeriod:0s ExperimentalPodPidsLimit:0 EnforceCPULimits:false CPUCFSQuotaPeriod:0s}
I1231 17:01:33.463276     625 container_manager_linux.go:295] Creating device plugin manager: false
E1231 17:01:33.467084     625 cpu_manager.go:135] [cpumanager] Unknown policy "", falling back to default policy "none"
I1231 17:01:33.478550     625 state_mem.go:36] [cpumanager] initializing new in-memory state store
I1231 17:01:33.492822     625 state_mem.go:84] [cpumanager] updated default cpuset: ""
I1231 17:01:33.495986     625 state_mem.go:92] [cpumanager] updated cpuset assignments: "map[]"
W1231 17:01:33.502520     625 csi_plugin.go:222] kubernetes.io/csi: kubeclient not set, assuming standalone kubelet
2019-12-31 17:01:33.506 +08:00 INFO core/module.go:41 module edged registered
2019-12-31 17:01:33.511 +08:00 INFO core/module.go:41 module websocket registered
2019-12-31 17:01:33.512 +08:00 INFO core/module.go:41 module eventbus registered
2019-12-31 17:01:33.514 +08:00 INFO core/module.go:41 module edgemesh registered
I1231 17:01:33.516159     625 db.go:37] DB meta for module metaManager has been registered
2019-12-31 17:01:33.518 +08:00 INFO core/module.go:41 module metaManager registered
2019-12-31 17:01:33.520 +08:00 INFO core/module.go:41 module servicebus registered
2019-12-31 17:01:33.522 +08:00 INFO core/module.go:44 module testManager is not register, please check modules.yaml
table `device` already exists, skip
table `device_attr` already exists, skip
table `device_twin` already exists, skip
table `meta` already exists, skip
2019-12-31 17:01:33.607 +08:00 INFO core/core.go:23 starting module twin
I1231 17:01:33.611078     625 dtcontroller.go:185] Begin to sync sqlite 
2019-12-31 17:01:33.620 +08:00 INFO core/core.go:23 starting module edged
2019-12-31 17:01:33.630 +08:00 INFO core/core.go:23 starting module websocket
I1231 17:01:33.633520     625 websocket.go:48] Websocket start to connect Access
2019-12-31 17:01:33.666 +08:00 INFO core/core.go:23 starting module eventbus
I1231 17:01:33.670764     625 server.go:126] Subscribe internal topic to $hw/events/upload/#
I1231 17:01:33.671530     625 server.go:126] Subscribe internal topic to $hw/events/device/+/state/update
I1231 17:01:33.688602     625 server.go:126] Subscribe internal topic to $hw/events/device/+/twin/+
I1231 17:01:33.691298     625 server.go:126] Subscribe internal topic to $hw/events/node/+/membership/get
I1231 17:01:33.693744     625 server.go:126] Subscribe internal topic to SYS/dis/upload_records
2019-12-31 17:01:33.692 +08:00 INFO core/core.go:23 starting module edgemesh
2019-12-31 17:01:33.708 +08:00 INFO core/core.go:23 starting module metaManager
2019-12-31 17:01:33.694 +08:00 DEBUG loadbalancer/strategy.go:23 Installed strategy plugin: RoundRobin.
W1231 17:01:33.736283     625 proxy.go:78] [L4 Proxy] create Device is failed : operation not supported
2019-12-31 17:01:33.732 +08:00 INFO core/core.go:23 starting module servicebus
I1231 17:01:33.739747     625 tcp.go:27] start listening at 172.17.0.1:8080
I1231 17:01:34.023391     625 cpu_manager.go:155] [cpumanager] starting with none policy
I1231 17:01:34.025776     625 cpu_manager.go:156] [cpumanager] reconciling every 0s
I1231 17:01:34.027894     625 policy_none.go:42] [cpumanager] none policy: Start
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x1d1440c]

goroutine 77 [running]:
github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).enforceNodeAllocatableCgroups(0x3cec3c0, 0x6, 0x0)
        /home/ubuntu/kubeedge/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/cm/node_container_manager_linux.go:78 +0x144
github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).setupNode(0x3cec3c0, 0x40905a0, 0x0, 0x11)
        /home/ubuntu/kubeedge/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go:437 +0xa8
github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).Start(0x3cec3c0, 0x0, 0x40905a0, 0x2899eb0, 0x3b2daa0, 0xa539cd58, 0x3e77800, 0x28e30a0, 0x3dc0fe0, 0x0, ...)
        /home/ubuntu/kubeedge/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go:588 +0xd4
github.com/kubeedge/kubeedge/edge/pkg/edged.(*edged).initializeModules(0x3caa000, 0x3e77800, 0x3d48100)
        /home/ubuntu/kubeedge/src/github.com/kubeedge/kubeedge/edge/pkg/edged/edged.go:639 +0xf4
github.com/kubeedge/kubeedge/edge/pkg/edged.(*edged).Start(0x3caa000, 0x3e61380)
        /home/ubuntu/kubeedge/src/github.com/kubeedge/kubeedge/edge/pkg/edged/edged.go:294 +0x35c
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.StartModules
        /home/ubuntu/kubeedge/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:22 +0x124
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
evertytime.

**Anything else we need to know?**:
when i run edgecore on ubuntu os, it is ok.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
cross comiple from 1.1.0 release souce.

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel

- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"

- Kernel (e.g. `uname -a`):
Linux ubuntu 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): 
go version go1.12.14 linux/amd64
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
cross compile from v1.1.0 release source code.

- Hardware configuration (e.g. `lscpu`):
cpu info:
```
processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 795.44
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32 
```
- OS (e.g. `cat /etc/os-release`):
build rootfs from buildroot.

- Kernel (e.g. `uname -a`):
Linux buildroot 4.14.67 #1 SMP PREEMPT Tue Dec 3 19:41:28 CST 2019 armv7l GNU/Linux

- Go version (e.g. `go version`): 
- Others:
docker version:
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.9.7
 Git commit:   89658be
 Built:        Tue Dec  3 19:08:34 CST 2019
 OS/Arch:      linux/arm
```
file edgecore
```
edgecore_arm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, Go BuildID=rohdppGJPSPNiStpGtjf/apLasouuLOHu_KoIGQ-q/tHN1evOAQ3SJPJfOzgZo/3ErTk-odWWNylllEg_uN, BuildID[sha1]=56f5441b328057e137865cf0c58011a3588abb49, not stripped
```

maybe cant run on arm, or something wrong of the operation?

thanks.

**Comment by bitvijays** [comment]
@latelee Did you compiled the edgecore on the arm machine? Also, did you changed the following line

```
 podsandbox-image: kubeedge/pause:3.1 # kubeedge/pause:3.1 for x86 arch , kubeedge/pause-arm:3.1 for arm arch, kubeedge/pause-arm64 for arm64 arch
``` 

in edge.yaml

Also, how have you installed the cloudcore? using keadm or compiled?

**Comment by latelee** [comment]
@bitvijays
I cross compile edgecore on ubuntu(x86) following https://docs.kubeedge.io/en/latest/setup/cross-compilation.html.I also change the edge.yaml.
futhermore, I install k8s(using kubeadm), cloudcore on one ubuntu(x86) os, and edgecore on another, I can get the right thing. just failed on armv7l.
I will try again, and update here if there‘s some good news.

**Comment by latelee** [comment]
I tried again today, still failed, some output info: 
```
[L4 Proxy] Add ip is failed : [L4 Proxy] Device edge0 is not exist!! please checkout the env
panic: runtime error: index out of range

goroutine 119 [running]:
github.com/kubeedge/kubeedge/edgemesh/pkg/proxy.addServer(0x3f61120, 0x14, 0x427e300, 0x2, 0x2)
        /home/ubuntu/kubeedge/src/github.com/kubeedge/kubeedge/edgemesh/pkg/proxy/proxy.go:388 +0x8f4
```
I figure out that there is no edge0 on my ARM target board.
But I found it on my Ubuntu os: 
```
# find / -name "edge0"
/sys/devices/virtual/net/edge0
/sys/class/net/edge0
```
Maybe there is sth that I miss,  try again later.

**Comment by latelee** [comment]
I found the reason of `panic: runtime error: index out of range`，
file kubeedge/edgemesh/pkg/proxy/proxy.go, function `addServer`:  
```
 if len(unused) == 0 { 
 	expandIpPool() 
 } 
 ip = unused[0] 
 unused = unused[1:] 
```
see the issue: https://github.com/kubeedge/kubeedge/issues/1181
When I fixed the bug, the edge node is ready(see edge-node-arm):
```
# kubectl get nodes
NAME            STATUS   ROLES    AGE    VERSION
edge-node       Ready    edge     6d5h   v1.15.3-kubeedge-v1.1.0-beta.0.323+52dd841358b292
edge-node-arm   Ready    edge     6h6m   v1.15.3-kubeedge-v1.1.0-beta.0.323+52dd841358b292-dirty
ubuntu          Ready    master   6d7h   v1.17.0
```
But still got the error:
```
I0106 22:44:28.682395    3562 generic.go:81] GenericLifecycle: Relisting
W0106 22:44:29.026038    3562 proxy.go:76] [L4 Proxy] create Device is failed : operation not supported
I0106 22:44:29.689864    3562 generic.go:81] GenericLifecycle: Relisting
I0106 22:44:30.697860    3562 generic.go:81] GenericLifecycle: Relisting
W0106 22:44:31.068954    3562 proxy.go:76] [L4 Proxy] create Device is failed : operation not supported
I0106 22:44:31.705060    3562 generic.go:81] GenericLifecycle: Relisting
I0106 22:44:32.724408    3562 generic.go:81] GenericLifecycle: Relisting
W0106 22:44:33.117475    3562 proxy.go:76] [L4 Proxy] create Device is failed : operation not supported
I0106 22:44:33.307057    3562 communicate.go:148] CheckConfirm
```
I had no idea about this.

**Comment by latelee** [comment]
I found the real reason is that, there is no edge0 device on my target board.
1. When I checked vishvananda source, it open `/dev/net/tun` somewhere, so I checked on my board but found nothing.
2. I found that my kernel didn't add CONFIG_TUN , so I turned it on, and recompiled kernel.
3. try deploy again, everything is ok.
```
# kubectl get nodes                
NAME            STATUS     ROLES    AGE     VERSION
edge-node       NotReady   edge     7d22h   v1.15.3-kubeedge-v1.1.0-beta.0.323+52dd841358b292
edge-node-arm   Ready      edge     46h     v1.15.3-kubeedge-v1.1.0-beta.0.323+52dd841358b292-dirty
ubuntu          Ready      master   7d23h   v1.17.0
```

I will close it.
