### ISSUE TITLE
base resource install kubeEdge v1.2  , i meet two  unimaginably queer problem ; this is second problem  基于源码部署的，执行创建svc后 cloudcore进程会挂掉

### ISSUE THREAD

**Issue by 379763376** [kubeedge/kubeedge#1481]
1.svc.yaml文件如下：
```
apiVersion: v1
kind: Service
metadata:
  name: my-httpd-svc
  namespace: default
spec:
  clusterIP: None
  selector:
    app: my-httpd

```
2.报错日志如下：my-nginx-svc已经删除 但是后台日志一直在查看这个的状态
```
E0220 11:47:50.432364   10360 channelq.go:197] fail to get message DeletionTimestamp for message: aa7b1f18-eb16-4f50-930c-af07c00f9e77
I0220 11:47:50.432378   10360 util.go:88] The resource type is pod, 3
E0220 11:47:50.432388   10360 channelq.go:197] fail to get message DeletionTimestamp for message: 47a267ca-8d6a-4ee6-8c71-7568d2d22130
I0220 11:47:50.432401   10360 util.go:88] The resource type is service, 3
E0220 11:47:50.432412   10360 channelq.go:197] fail to get message DeletionTimestamp for message: 858ff06e-78bf-455e-870e-43ba35dae80c
I0220 11:47:50.432437   10360 util.go:88] The resource type is endpoints, 3
I0220 11:47:50.432450   10360 util.go:88] The resource type is endpoints, 3
I0220 11:47:50.432462   10360 util.go:113] The resource name is kube-controller-manager, 4
I0220 11:47:50.432150   10360 objectsync.go:116] The resourceVersion: 1164220 of service in K8s is greater than in edgenode: 1034041, send the update event
I0220 11:47:50.432501   10360 objectsync.go:116] The resourceVersion: 1164221 of endpoints in K8s is greater than in edgenode: 752253, send the update event
I0220 11:47:50.432531   10360 objectsync.go:108] endpoints: my-nginx-svc has been deleted in K8s, send the delete event to edge
E0220 11:47:50.432550   10360 objectsync.go:141] object is nil
I0220 11:47:50.432585   10360 objectsync.go:116] The resourceVersion: 1164220 of service in K8s is greater than in edgenode: 1034375, send the update event
I0220 11:47:50.432610   10360 objectsync.go:116] The resourceVersion: 859414 of endpoints in K8s is greater than in edgenode: 114804, send the update event
I0220 11:47:50.432636   10360 objectsync.go:108] service: my-nginx-svc has been deleted in K8s, send the delete event to edge
E0220 11:47:50.432655   10360 objectsync.go:141] object is nil
I0220 11:47:50.432672   10360 objectsync.go:116] The resourceVersion: 1164226 of endpoints in K8s is greater than in edgenode: 753346, send the update event
I0220 11:47:50.432696   10360 objectsync.go:108] service: my-nginx-svc has been deleted in K8s, send the delete event to edge
E0220 11:47:50.432713   10360 objectsync.go:141] object is nil
I0220 11:47:50.432726   10360 objectsync.go:116] The resourceVersion: 1164220 of service in K8s is greater than in edgenode: 753366, send the update event
I0220 11:47:50.432750   10360 objectsync.go:116] The resourceVersion: 1164218 of endpoints in K8s is greater than in edgenode: 979691, send the update event
E0220 11:47:50.432919   10360 runtime.go:78] Observed a panic: &strconv.NumError{Func:"ParseUint", Num:"", Err:(*errors.errorString)(0xc0000ae1b0)} (strconv.ParseUint: parsing "": invalid syntax)
goroutine 423 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14509a0, 0xc0008945d0)
	/home/gowork/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/gowork/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14509a0, 0xc0008945d0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.CompareResourceVersion(0xc0010b4380, 0x7, 0x0, 0x0, 0x0)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:166 +0x10d
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.sendEvents(0x0, 0x0, 0xc00095e520, 0x16, 0xc000339df9, 0x7, 0xc000339e30, 0xc, 0x1622850, 0x7, ...)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:114 +0x85
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).manageService(0xc000255c80, 0xc000a199c8)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:70 +0x23a
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).manageObjectSync(0xc000255c80, 0xc000a42000, 0x3d, 0x40)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:216 +0x233
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).reconcile(0xc000255c80)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:193 +0x1ea
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000ac3bc0)
	/home/gowork/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ac3bc0, 0x12a05f200, 0x0, 0x1, 0xc0003f0000)
	/home/gowork/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000ac3bc0, 0x12a05f200, 0xc0003f0000)
	/home/gowork/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).Start
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:179 +0x510
panic: strconv.ParseUint: parsing "": invalid syntax [recovered]
	panic: strconv.ParseUint: parsing "": invalid syntax

goroutine 423 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/gowork/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/runtime/runtime.go:55 +0x105
panic(0x14509a0, 0xc0008945d0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.CompareResourceVersion(0xc0010b4380, 0x7, 0x0, 0x0, 0x0)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:166 +0x10d
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.sendEvents(0x0, 0x0, 0xc00095e520, 0x16, 0xc000339df9, 0x7, 0xc000339e30, 0xc, 0x1622850, 0x7, ...)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:114 +0x85
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).manageService(0xc000255c80, 0xc000a199c8)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:70 +0x23a
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).manageObjectSync(0xc000255c80, 0xc000a42000, 0x3d, 0x40)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:216 +0x233
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).reconcile(0xc000255c80)
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:193 +0x1ea
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000ac3bc0)
	/home/gowork/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ac3bc0, 0x12a05f200, 0x0, 0x1, 0xc0003f0000)
	/home/gowork/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000ac3bc0, 0x12a05f200, 0xc0003f0000)
	/home/gowork/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).Start
	/home/gowork/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:179 +0x510
```

**Comment by 379763376** [comment]
不报错的情况也会执行一段时间cloudcore和edgecore也会停掉

**Comment by 379763376** [comment]
e type is: kubeedge-edge-bolt
I0221 04:34:11.028097   14092 upstream.go:171] message: , operation type is: update
E0221 04:34:11.028120   14092 upstream.go:202] message: , resource type: kubeedge-edge-bolt unsupported
E0221 04:34:11.102745   14092 ws.go:122] failed to read message, error: websocket: close 1006 (abnormal closure): unexpected EOF
I0221 04:34:16.379152   14092 core.go:35] Get os signal hangup
I0221 04:34:16.380605   14092 core.go:40] Cleanup module cloudhub
W0221 04:34:16.380702   14092 upstream.go:489] stop queryConfigMap
I0221 04:34:16.380788   14092 upstream.go:108] Stop updateDeviceStatus
I0221 04:34:16.380827   14092 upstream.go:108] Stop updateDeviceStatus
I0221 04:34:16.380861   14092 upstream.go:108] Stop updateDeviceStatus

**Comment by 379763376** [comment]
when cloudcore run some time about one day,it will been done.
my kubeedge version is v1.2.0
```
e type is: kubeedge-edge-bolt
I0221 04:34:11.028097   14092 upstream.go:171] message: , operation type is: update
E0221 04:34:11.028120   14092 upstream.go:202] message: , resource type: kubeedge-edge-bolt unsupported
E0221 04:34:11.102745   14092 ws.go:122] failed to read message, error: websocket: close 1006 (abnormal closure): unexpected EOF
I0221 04:34:16.379152   14092 core.go:35] Get os signal hangup
I0221 04:34:16.380605   14092 core.go:40] Cleanup module cloudhub
W0221 04:34:16.380702   14092 upstream.go:489] stop queryConfigMap
I0221 04:34:16.380788   14092 upstream.go:108] Stop updateDeviceStatus
I0221 04:34:16.380827   14092 upstream.go:108] Stop updateDeviceStatus
I0221 04:34:16.380861   14092 upstream.go:108] Stop updateDeviceStatus
```

**Comment by fisherxu** [comment]
@379763376 Are you trying edgemesh?

**Comment by 379763376** [comment]
> @379763376 Are you trying edgemesh?

Thanks, I am trying how to use the KubeEdge.  It'll stop even if I don't do anything

**Comment by 379763376** [comment]
my os is Centos7.7
cloudcore config is:
```
apiVersion: cloudcore.config.kubeedge.io/v1alpha1
kind: CloudCore
kubeAPIConfig:
  kubeConfig: /root/.kube/config
  master: ""
modules:
  cloudhub:
    nodeLimit: 10
    tlsCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/edge.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key
    unixsocket:
      address: unix:///var/lib/kubeedge/kubeedge.sock
      enable: true
    websocket:
      address: 0.0.0.0
      enable: true
      port: 10000
```

edgecore config is :
```
apiVersion: edgecore.config.kubeedge.io/v1alpha1
database:
  dataSource: /var/lib/kubeedge/edgecore.db
kind: EdgeCore
modules:
  edged:
    cgroupDriver: systemd
    clusterDNS: ""
    clusterDomain: ""
    devicePluginEnabled: false
    dockerAddress: unix:///var/run/docker.sock
    gpuPluginEnabled: false
    hostnameOverride: kubeedge-edge-bolt
    interfaceName: eth0
    nodeIP: $edgecoreIp
    podSandboxImage: kubeedge/pause:3.1
    remoteImageEndpoint: unix:///var/run/dockershim.sock
    remoteRuntimeEndpoint: unix:///var/run/dockershim.sock
    runtimeType: docker
  edgehub:
    heartbeat: 15
    tlsCaFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/edge.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key
    websocket:
      enable: true
      handshakeTimeout: 30
      readDeadline: 15
      server: $cloudcoreIp:10000
      writeDeadline: 15
  eventbus:
    mqttMode: 0
    mqttQOS: 0
    mqttRetain: false
    mqttServerExternal: tcp://127.0.0.1:1883
    mqttServerInternal: tcp://127.0.0.1:1884

```

**Comment by fisherxu** [comment]
It seems that the config is correct

**Comment by Penny20181222** [comment]
We meet the same problem, have it been fixed?

**Comment by 379763376** [comment]
No, each test is manually restarted

**Comment by 379763376** [comment]
解决了 即便是nohup xxx &启动，也需要exit出xshell。直接关闭xshell的话就会停止

**Comment by zqdlove** [comment]
v1.2.1 , meet the same problem.
