### ISSUE TITLE
keadm init error

### ISSUE THREAD

**Issue by majoyz** [kubeedge/kubeedge#1556]
**What happened**:
I want to reinstall kubeedge by keadm, after using "keadm init" on master, it showed an err: 

```
F0324 13:47:44.652470   23191 keadm.go:27] failed to run command(cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v1.2.1-linux-amd64.tar.gz && cp /etc/kubeedge//kubeedge-v1.2.1-linux-amd64/cloud/cloudcore/cloudcore /usr/local/bin/), err:exit status 2
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0002e1e00, 0xc0004622c0, 0x104, 0x158)
	/root/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:883 +0xb8
k8s.io/klog.(*loggingT).output(0x1ea4c60, 0xc000000003, 0xc00010a700, 0x1e1fcae, 0x8, 0x1b, 0x0)
	/root/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:834 +0x330
k8s.io/klog.(*loggingT).printDepth(0x1ea4c60, 0xc000000003, 0x1, 0xc000025f40, 0x1, 0x1)
	/root/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:706 +0x129
k8s.io/klog.(*loggingT).print(...)
	/root/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:697
k8s.io/klog.Fatal(...)
	/root/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1264
main.main()
	/root/go/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0x8a
```

How to fix it?
Where can I know the meaning of those exit status?

**Comment by fisherxu** [comment]
which version of keadm do you used?

**Comment by majoyz** [comment]
> which version of keadm do you used?

the latest

**Comment by fisherxu** [comment]
cp /etc/kubeedg**e//k**ubeedge-v1.2.1-linux-amd64, has a duplicate `/` here, seems a bug, but in my env it works fine.. 
![image](https://user-images.githubusercontent.com/28776356/77418061-54813d00-6e01-11ea-9131-547de6f99ba6.png)
My os is ubuntu 16.04, what's your os arch and version?

**Comment by majoyz** [comment]
> cp /etc/kubeedg**e//k**ubeedge-v1.2.1-linux-amd64, has a duplicate `/` here, seems a bug, but in my env it works fine..
> ![image](https://user-images.githubusercontent.com/28776356/77418061-54813d00-6e01-11ea-9131-547de6f99ba6.png)
> My os is ubuntu 16.04, what's your os arch and version?

yes,  but there are same command in some 2019's issues, like [issue#1139](https://github.com/kubeedge/kubeedge/issues/1139), so I think the duplicate `/` is ok.
My os is CentOS 7.6.

**Comment by fisherxu** [comment]
It seems failed to exec this cmd `cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v1.2.1-linux-amd64.tar.gz && cp /etc/kubeedge//kubeedge-v1.2.1-linux-amd64/cloud/cloudcore/cloudcore /usr/local/bin/`, but in my env and travis CI all works fine...
