### ISSUE TITLE
Update upstream dependency to K8s 1.18

### ISSUE THREAD

**Issue by dingyin** [kubeedge/kubeedge#1933]
**What would you like to be added/modified**:
Upstream K8s is 1.18, we need to update upstream dependency.

**Why is this needed**:
We need to update upstream dependency to avoid more issues when upgrade to 1.19 in the future.

**Comment by zzxgzgz** [comment]
I updated k8s to 1.18.5, you can see it in my [repo's k8s_1.18.5 branch](https://github.com/zzxgzgz/kubeedge-1/tree/k8s_1.18.5).

However, when I run the keadm_e2e test, it failed with this error:
```
I0715 23:05:22.346278   28883 edged_pods.go:293] container: default/pod-app-u50ox/nginx podIP: "172.17.0.3" creating hosts mount: true
I0715 23:05:22.346301   28883 edged_pods.go:375] Pod "pod-app-u50ox_default(380a9b8f-2f58-4490-b5df-b0b4cdc487ab)" container "nginx" mount "default-token-dlndm" has propagation "PROPAGATION_HOST_TO_CONTAINER"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x26d8e35]
  
goroutine 631 [running]:
k8s.io/kubernetes/pkg/kubelet/cm/cpumanager.(*manager).AddContainer(0xc0005dd170, 0xc0010b8c00, 0xc000d35180, 0xc0006d6540, 0x40, 0x0, 0x0)
        /home/go/pkg/mod/k8s.io/kubernetes@v1.18.0/pkg/kubelet/cm/cpumanager/cpu_manager.go:232 +0x55
github.com/kubeedge/kubeedge/edge/pkg/edged/clcm.(*internalContainerLifecycleImpl).PreStartContainer(0xc000900610, 0xc0010b8c00, 0xc000d35180, 0xc0006d6540, 0x40, 0xc0006d6540, 0x40)
        /home/go/src/github.com/zzxgzgz/kubeedge-1/edge/pkg/edged/clcm/internal_life_cycle.go:45 +0x93
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).startContainer(0xc0002afe60, 0xc00128b040, 0x40, 0xc00046e1c0, 0xc00083a090, 0xc0010b8c00, 0xc0006a7c00, 0x0, 0x0, 0x0, ...)
        /home/go/pkg/mod/k8s.io/kubernetes@v1.18.0/pkg/kubelet/kuberuntime/kuberuntime_container.go:182 +0x9f4
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod.func1(0x3220c4a, 0x9, 0xc00083a090, 0xc00046e100, 0x0)
        /home/go/pkg/mod/k8s.io/kubernetes@v1.18.0/pkg/kubelet/kuberuntime/kuberuntime_manager.go:793 +0x8ce
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod(0xc0002afe60, 0xc0010b8c00, 0xc0006a7c00, 0x0, 0x0, 0x0, 0xc0005a3180, 0xc00083a0b0, 0x2, 0x2, ...)
        /home/go/pkg/mod/k8s.io/kubernetes@v1.18.0/pkg/kubelet/kuberuntime/kuberuntime_manager.go:832 +0xc16
github.com/kubeedge/kubeedge/edge/pkg/edged.(*edged).consumePodAddition(0xc000965180, 0xc000f73f40, 0x21, 0xbfbc00cc2ad9abcd)
        /home/go/src/github.com/zzxgzgz/kubeedge-1/edge/pkg/edged/edged.go:932 +0x861
github.com/kubeedge/kubeedge/edge/pkg/edged.(*edged).podAddWorkerRun.func1(0xc000965180, 0x0)
        /home/go/src/github.com/zzxgzgz/kubeedge-1/edge/pkg/edged/edged.go:845 +0x490
created by github.com/kubeedge/kubeedge/edge/pkg/edged.(*edged).podAddWorkerRun
        Killedgo/src/github.com/zzxgzgz/kubeedge-1/edge/pkg/edged/edged.go:824 +0xc9
```

Full log is attached here: 
[edgecore.log](https://github.com/kubeedge/kubeedge/files/4928486/edgecore.log)



Does anyone know how to fix this?

Thank you.

**Comment by daixiang0** [comment]
@dingyin i would like to do it if possible.
