### ISSUE TITLE
beehive function beehiveContext.SendToGroup report error: the message channel is full

### ISSUE THREAD

**Issue by Yellow-L** [kubeedge/kubeedge#2105]
**What happened**:
function beehiveContext.SendToGroup report waring: the message channel is full
```
W0825 10:18:58.261329       1 context_channel.go:175] the message channel is full, message: {Header:{ID:94a47340-01c0-49e8-b5b6-8ecd59129b45 ParentID: Timestamp:1598350737152 ResourceVersion: Sync:false} Router:{Source:edged Group:meta Operation:insert Resource:node/55c9c69a43294cc2b69ff5f50a148561/default/nodestatus/55c9c69a43294cc2b69ff5f50a148561} Content:map[metadata:map[creationTimestamp:<nil> labels:map[kubernetes.io/arch:amd64 kubernetes.io/hostname:55c9c69a43294cc2b69ff5f50a148561 kubernetes.io/os:linux node-role.kubernetes.io/agent: node-role.kubernetes.io/edge:]] spec:map[] status:map[addresses:[map[address:192.168.122.134 type:InternalIP] map[address:55c9c69a43294cc2b69ff5f50a148561 type:Hostname]] allocatable:map[cpu:2 memory:3851Mi pods:110] capacity:map[cpu:2 memory:3951Mi pods:110] daemonEndpoints:map[kubeletEndpoint:map[Port:0]] nodeInfo:map[architecture:amd64 bootID: containerRuntimeVersion:remote://18.9.6 kernelVersion:3.10.0-862.el7.x86_64 kubeProxyVersion: kubeletVersion:v1.17.1-kubeedge-v1.3.0-105+bffa530f200756 machineID: operatingSystem:linux osImage:CentOS Linux 7 (Core)/eyJlZGdlLmhjcC9hZGRyZXNzIjoiaGFpZGlhbiIsImVkZ2UuaGNwL2NpdHkiOiIxMTAxMDAwMDAwMDAiLCJlZGdlLmhjcC9kZXZpY2VfYnJhbmQiOiJsZW5vdm8iLCJlZGdlLmhjcC9kZXZpY2VfbW9kZWwiOiJ0ZXN0IiwiZWRnZS5oY3AvZGV2aWNlX251bWJlciI6IjU1YzljNjlhNDMyOTRjYzJiNjlmZjVmNTBhMTQ4NTYxIiwiZWRnZS5oY3AvbGF0aXR1ZGUiOiI0MC4wNDMiLCJlZGdlLmhjcC9sb25ndGl0dWRlIjoiMTE2LjMxNCIsImVkZ2UuaGNwL3Byb3ZpbmNlcyI6IjExMDAwMDAwMDAwMCJ9 systemUUID:]]]}

```
**What you expected to happen**:
no waring and channel is not blocked.
**How to reproduce it (as minimally and precisely as possible)**:
still don't know, my cluster have 400 edge nodes, 15 edge nodes status NotReady.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.0

**Comment by daixiang0** [comment]
Any reproduce steps?

**Comment by luogangyi** [comment]
The default channel size is 1024
see “ChannelSizeDefault = 1024” in staging/src/github.com/kubeedge/beehive/pkg/core/context/context_channel.go

I think you can try to change it to 2048 and see if problem solved.

Waiting for your result :)  If it turns out to be OK, we can make this option to be configurable.

**Comment by Yellow-L** [comment]
Yes, the default channel size is 1024, I'll try it to 2048 later.

**Comment by Yellow-L** [comment]
Change channel size to 2048 can't solve this problem, clean all nodes and re-join 500 nodes could reproduce it.

**Comment by luogangyi** [comment]
> @daixiang0 @luogangyi Maybe the channel size is not the reason of this problem, I increased the apiserver QPS parameter of cloudcore, then more edgenode could register to cloudcore and edgecontroller read data from channel more quickly, warning disappeared.

So, if we add edge node slowly, will it be OK ?

**Comment by Yellow-L** [comment]
Kubernetes APISERVER panic:
```
I0904 03:19:21.835634       1 trace.go:81] Trace[1756421485]: "List /apis/reliablesyncs.kubeedge.io/v1alpha1/objectsyncs" (started: 2020-09-04 03:19:08.87314888 +0000 UTC m=+48110.704250659) (total time: 12.962459731s):
Trace[1756421485]: [236.230365ms] [236.1427ms] Listing from storage done
Trace[1756421485]: [12.96245778s] [12.726227415s] Writing http response done (62681 items)
E0904 03:19:21.835805       1 runtime.go:73] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
goroutine 86367070 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3a432e0, 0xc000270340)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc002775ce0, 0x1, 0x1)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x3a432e0, 0xc000270340)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc04ad620a0, 0xc02af87220)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:238 +0x1a9
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00a518a00, 0x73a86e0, 0xc01f13ba40, 0xc019a88c00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:122 +0x2ab
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x73a86e0, 0xc01f13ba40, 0xc019a88b00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xf3
net/http.HandlerFunc.ServeHTTP(0xc007556b40, 0x73a86e0, 0xc01f13ba40, 0xc019a88b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x73a86e0, 0xc01f13ba40, 0xc021317b00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x2b8
net/http.HandlerFunc.ServeHTTP(0xc007556b70, 0x73a86e0, 0xc01f13ba40, 0xc021317b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x73a86e0, 0xc01f13ba40, 0xc021317b00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x127
net/http.HandlerFunc.ServeHTTP(0xc00a518a20, 0x739cfa0, 0xc0022daaa8, 0xc021317b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc007556ba0, 0x739cfa0, 0xc0022daaa8, 0xc021317b00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc00a653ad0, 0x739cfa0, 0xc0022daaa8, 0xc021317b00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.initNPNRequest.ServeHTTP(0xc03b60e380, 0xc00a653ad0, 0x739cfa0, 0xc0022daaa8, 0xc021317b00)
	/usr/local/go/src/net/http/server.go:3323 +0x8d
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00c1f5b00, 0xc0022daaa8, 0xc021317b00, 0xc00b979de0)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2125 +0x89
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1859 +0x4f4
E0904 03:19:21.835960       1 wrap.go:32] apiserver panic'd on GET /apis/reliablesyncs.kubeedge.io/v1alpha1/objectsyncs?limit=500&resourceVersion=0
I0904 03:19:21.836104       1 log.go:172] http2: panic serving 10.121.134.106:53846: killing connection/stream because serving request timed out and response had been started
goroutine 86367070 [running]:
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc0022daaa8, 0xc002775faf, 0xc00c1f5b00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2118 +0x16b
panic(0x3a432e0, 0xc000270340)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc002775ce0, 0x1, 0x1)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x3a432e0, 0xc000270340)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc04ad620a0, 0xc02af87220)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:238 +0x1a9
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00a518a00, 0x73a86e0, 0xc01f13ba40, 0xc019a88c00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:122 +0x2ab
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x73a86e0, 0xc01f13ba40, 0xc019a88b00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xf3
net/http.HandlerFunc.ServeHTTP(0xc007556b40, 0x73a86e0, 0xc01f13ba40, 0xc019a88b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x73a86e0, 0xc01f13ba40, 0xc021317b00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x2b8
net/http.HandlerFunc.ServeHTTP(0xc007556b70, 0x73a86e0, 0xc01f13ba40, 0xc021317b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x73a86e0, 0xc01f13ba40, 0xc021317b00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x127
net/http.HandlerFunc.ServeHTTP(0xc00a518a20, 0x739cfa0, 0xc0022daaa8, 0xc021317b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc007556ba0, 0x739cfa0, 0xc0022daaa8, 0xc021317b00)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc00a653ad0, 0x739cfa0, 0xc0022daaa8, 0xc021317b00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.initNPNRequest.ServeHTTP(0xc03b60e380, 0xc00a653ad0, 0x739cfa0, 0xc0022daaa8, 0xc021317b00)
	/usr/local/go/src/net/http/server.go:3323 +0x8d
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00c1f5b00, 0xc0022daaa8, 0xc021317b00, 0xc00b979de0)
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2125 +0x89
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1859 +0x4f4

```

**Comment by mixalako** [comment]
Hello , having the same problem with 3 edge nodes . 1-2 are notReady . How did you fix it in the end ?? Thanks.

**Comment by shenkonghui** [comment]
We also had this problem, when we were doing the disconnection test

**Comment by koulq** [comment]
hello，What is the configuration requirement of CloudCore for the cloud? Is there any official configuration recommendation? For example: CPU, memory, storage performance, now 40 nodes can not hold up, report the same error.

**Comment by CKchen0726** [comment]
Hello，the same problem occurs in a 7-nodes cluster
```
E0611 09:08:31.859207       1 objectsync.go:100] The ObjectResourceVersion is empty in status of objectsync: star2-orin03.a4a3c3a8-b9d3-4f49-a2d6-88d77ed85384
W0611 09:08:31.957263       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:4d4f9f34-a54b-420a-9bf5-d5ec923f7c1f ParentID: Timestamp:1749604253281 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:patch Resource:node/star2-orin03/default/event/star2-orin03.18457b2aa299a5c0} Content:[123 34 101 118 101 110 116 34 58 123 34 109 101 116 97 100 97 116 97 34 58 123 34 110 97 109 101 34 58 34 115 116 97 114 50 45 111 114 105 110 48 51 46 49 56 52 53 55 98 50 97 97 50 57 57 97 53 99 48 34 44 34 110 97 109 101 115 112 97 99 101 34 58 34 100 101 102 97 117 108 116 34 44 34 99 114 101 97 116 105 111 110 84 105 109 101 115 116 97 109 112 34 58 110 117 108 108 125 44 34 105 110 118 111 108 118 101 100 79 98 106 101 99 116 34 58 123 34 107 105 110 100 34 58 34 78 111 100 101 34 44 34 110 97 109 101 34 58 34 115 116 97 114 50 45 111 114 105 110 48 51 34 44 34 117 105 100 34 58 34 115 116 97 114 50 45 111 114 105 110 48 51 34 125 44 34 114 101 97 115 111 110 34 58 34 78 111 100 101 72 97 115 83 117 102 102 105 99 105 101 110 116 77 101 109 111 114 121 34 44 34 109 101 115 115 97 103 101 34 58 34 78 111 100 101 32 115 116 97 114 50 45 111 114 105 110 48 51 32 115 116 97 116 117 115 32 105 115 32 110 111 119 58 32 78 111 100 101 72 97 115 83 117 102 102 105 99 105 101 110 116 77 101 109 111 114 121 34 44 34 115 111 117 114 99 101 34 58 123 34 99 111 109 112 111 110 101 110 116 34 58 34 107 117 98 101 108 101 116 34 44 34 104 111 115 116 34 58 34 115 116 97 114 50 45 111 114 105 110 48 51 34 125 44 34 102 105 114 115 116 84 105 109 101 115 116 97 109 112 34 58 34 50 48 50 53 45 48 54 45 48 51 84 48 56 58 51 48 58 53 51 90 34 44 34 108 97 115 116 84 105 109 101 115 116 97 109 112 34 58 34 50 48 50 53 45 48 54 45 49 49 84 48 49 58 49 48 58 53 51 90 34 44 34 99 111 117 110 116 34 58 50 55 56 54 50 44 34 116 121 112 101 34 58 34 78 111 114 109 97 108 34 44 34 101 118 101 110 116 84 105 109 101 34 58 110 117 108 108 44 34 114 101 112 111 114 116 105 110 103 67 111 109 112 111 110 101 110 116 34 58 34 107 117 98 101 108 101 116 34 44 34 114 101 112 111 114 116 105 110 103 73 110 115 116 97 110 99 101 34 58 34 115 116 97 114 50 45 111 114 105 110 48 51 34 125 44 34 112 97 116 99 104 68 97 116 97 34 58 34 123 92 34 99 111 117 110 116 92 34 58 50 55 56 54 50 44 92 34 108 97 115 116 84 105 109 101 115 116 97 109 112 92 34 58 92 34 50 48 50 53 45 48 54 45 49 49 84 48 49 58 49 48 58 53 51 90 92 34 44 92 34 109 101 115 115 97 103 101 92 34 58 92 34 78 111 100 101 32 115 116 97 114 50 45 111 114 105 110 48 51 32 115 116 97 116 117 115 32 105 115 32 110 111 119 58 32 78 111 100 101 72 97 115 83 117 102 102 105 99 105 101 110 116 77 101 109 111 114 121 92 34 125 34 125]}
W0611 09:08:32.563723       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:d79348c3-9acb-456d-a203-f12242c415b3 ParentID: Timestamp:1749240866381 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star1-orin03/kube-node-lease/lease/star1-orin03} Content:[]}
W0611 09:08:32.944304       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:c10aacd0-9dbc-471a-b004-46f8263e0763 ParentID: Timestamp:1749240926763 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star1-orin03/default/node/star1-orin03} Content:[]}
W0611 09:08:33.210180       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:cdd06003-0479-40c6-8a59-3bdf752b408b ParentID: Timestamp:1750947619322 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star1-orin01/kube-node-lease/lease/star1-orin01} Content:[]}
W0611 09:08:33.306381       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:b2f00a07-005b-4a4d-ac55-527e8939de6c ParentID: Timestamp:1749658257252 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star2-orin01/default/node/star2-orin01} Content:[]}
W0611 09:08:33.339895       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:2245da4c-b2ab-44fd-8adf-9772c1a5939f ParentID: Timestamp:1749658221031 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star2-orin02/kube-node-lease/lease/star2-orin02} Content:[]}
W0611 09:08:33.434810       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:31f28ef6-4953-4433-ae9a-c0432324ac21 ParentID: Timestamp:1749604194747 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star2-orin03/kube-node-lease/lease/star2-orin03} Content:[]}
W0611 09:08:33.863717       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:ad485102-8499-444a-a542-e5981023b04d ParentID: Timestamp:1749604136487 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star1-orin02/kube-node-lease/lease/star1-orin02} Content:[]}
W0611 09:08:34.946242       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:da211c06-a822-45eb-9877-ff4f29e928fc ParentID: Timestamp:1749240868763 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star1-orin03/default/node/star1-orin03} Content:[]}
W0611 09:08:35.145518       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:181a95eb-0138-49ba-bc2d-6e5783f1f690 ParentID: Timestamp:1749604024723 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star3-orin01/kube-node-lease/lease/star3-orin01} Content:[]}
W0611 09:08:35.387994       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:364013ee-4c84-4808-aebc-2d13d518be68 ParentID: Timestamp:1749604198013 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star1-orin02/default/node/star1-orin02} Content:[]}
W0611 09:08:35.603550       1 context_channel.go:180] The module edgecontroller message channel is full, message: {Header:{ID:ffa470c8-49d6-4027-91ef-f217f21f5f4e ParentID: Timestamp:1749658199548 ResourceVersion: Sync:false MessageType:} Router:{Source:edged Destination: Group:meta Operation:query Resource:node/star2-orin01/kube-node-lease/lease/star2-orin01} Content:[]}

```
