### ISSUE TITLE
Error: can't support this architecture of CentOS: aarch64

### ISSUE THREAD

**Issue by ShaPoHun** [kubeedge/kubeedge#2124]
## problem
```
[root@k8s-master ~]# keadm init --advertise-address="192.168.8.86"
Kubernetes version verification passed, KubeEdge installation will start...
Error: can't support this architecture of CentOS: aarch64
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.2.1  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver


Flags:
      --advertise-address string   Use this key to set SANs in certificate of cloudcore. eg: 10.10.102.78,10.10.102.79
  -h, --help                       help for init
      --kube-config string         Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string    Use this key to download and use the required KubeEdge version
      --master string              Use this key to set K8s master address, eg: http://127.0.0.1:8080

F0903 10:40:52.701749   27663 keadm.go:27] can't support this architecture of CentOS: aarch64
goroutine 1 [running]:
k8s.io/klog.stacks(0x400037a100, 0x400002e000, 0x5e, 0xb2)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:883 +0xac
k8s.io/klog.(*loggingT).output(0x1a26f00, 0x4000000003, 0x400051a000, 0x1993c5d, 0x8, 0x1b, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:834 +0x3d0
k8s.io/klog.(*loggingT).printDepth(0x1a26f00, 0x4000000003, 0x1, 0x4000455f58, 0x1, 0x1)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:706 +0x100
k8s.io/klog.(*loggingT).print(...)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:697
k8s.io/klog.Fatal(...)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:1264
main.main()
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0x74
```

## System and software environment
```
[root@k8s-master ~]# uname -a
Linux k8s-master 4.18.0-193.1.2.el7.aarch64 #1 SMP Fri May 29 18:22:47 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
[root@k8s-master ~]# keadm version
version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"dfcdab01d4538ebefc2284a1b82a407d649e8f94", GitTreeState:"clean", BuildDate:"2020-08-14T09:46:23Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/arm64"}
```

## How to solve it?

**Comment by GsssC** [comment]
It seems that AArch64 and ARM64 refer to the same thing by [Differences between arm64 and aarch64](https://stackoverflow.com/questions/31851611/differences-between-arm64-and-aarch64)

Have you tried succesfully run [kubeedge-v1.4.0-linux-arm64.tar.gz](https://github.com/kubeedge/kubeedge/releases/download/v1.4.0/kubeedge-v1.4.0-linux-arm64.tar.gz) manually on your device? 

If not maybe you need build, install and run cloudcore manually Imitating the following steps [Cross compile](https://github.com/kubeedge/kubeedge/blob/master/docs/setup/build.md).

**Comment by ShaPoHun** [comment]
> It seems that AArch64 and ARM64 refer to the same thing by [Differences between arm64 and aarch64](https://stackoverflow.com/questions/31851611/differences-between-arm64-and-aarch64)
> 
> Have you succesfully run [kubeedge-v1.4.0-linux-arm64.tar.gz](https://github.com/kubeedge/kubeedge/releases/download/v1.4.0/kubeedge-v1.4.0-linux-arm64.tar.gz) on your device?
> 
> If not maybe you need build, install and run cloudcore manually Imitating the following steps [Cross compile](https://github.com/kubeedge/kubeedge/blob/master/docs/setup/build.md).

I have recompiled on AArch64 , but it still doesn't work.

It may be that the code does not support this architecture on centos.

Below is the result of my compiler:
```
[root@k8s-master kubeedge]# make all WHAT=keadm
bash hack/verify-golang.sh
go detail version: go version go1.14.4 linux/arm64
go version: 1.14.4
hack/make-rules/build.sh keadm
building github.com/kubeedge/kubeedge/keadm/cmd/keadm
+ go build -o /root/go/src/github.com/kubeedge/kubeedge/_output/local/bin/keadm -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2020-09-03T09:58:03Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=3d9db55b9dc3123c8fc120fb427d5c8f65ee3be1 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.4.0-beta.0.75+3d9db55b9dc312 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=4+' github.com/kubeedge/kubeedge/keadm/cmd/keadm
+ set +x
[root@k8s-master kubeedge]# make all WHAT=cloudcore && make all WHAT=edgecore
bash hack/verify-golang.sh
go detail version: go version go1.14.4 linux/arm64
go version: 1.14.4
hack/make-rules/build.sh cloudcore
building github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
+ go build -o /root/go/src/github.com/kubeedge/kubeedge/_output/local/bin/cloudcore -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2020-09-03T09:58:39Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=3d9db55b9dc3123c8fc120fb427d5c8f65ee3be1 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.4.0-beta.0.75+3d9db55b9dc312 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=4+' github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
+ set +x
bash hack/verify-golang.sh
go detail version: go version go1.14.4 linux/arm64
go version: 1.14.4
hack/make-rules/build.sh edgecore
building github.com/kubeedge/kubeedge/edge/cmd/edgecore
+ go build -o /root/go/src/github.com/kubeedge/kubeedge/_output/local/bin/edgecore -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2020-09-03T09:58:57Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=3d9db55b9dc3123c8fc120fb427d5c8f65ee3be1 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.4.0-beta.0.75+3d9db55b9dc312 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=4+' github.com/kubeedge/kubeedge/edge/cmd/edgecore
+ set +x

```

golang environment:
```
[root@k8s-master bin]# go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/go/src/github.com/kubeedge/kubeedge/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build370813229=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by ShaPoHun** [comment]
https://github.com/kubeedge/kubeedge/blob/01d49fe8bbabf3f9d74db4a4affe5a64c7d19a41/keadm/cmd/keadm/app/cmd/util/centosinstaller.go#L78-L94

**Only x86 is supported on centos.**

**Comment by GsssC** [comment]
keadm certainly dont support, kubeedge(cloudcore and edgecore) may can

**Comment by daixiang0** [comment]
@ShaPoHun you can add case check at local to test, if succeed, you can post a pr to fix this.
