### ISSUE TITLE
keadm init failed with Error: not able to create /var/log/kubeedge/ folder path

### ISSUE THREAD

**Issue by echo467** [kubeedge/kubeedge#2477]
**What happened and what you expected to happen**:
### here comes the details
```bash
$ sudo ./_output/local/bin/keadm init
Kubernetes version verification passed, KubeEdge installation will start...
Error: not able to create /var/log/kubeedge/ folder path
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.5.0  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver


Flags:
      --advertise-address string   Use this key to set IPs in cloudcore's certificate SubAltNames field. eg: 10.10.102.78,10.10.102.79
      --domainname string          Use this key to set domain names in cloudcore's certificate SubAltNames field. eg: www.cloudcore.cn,www.kubeedge.cn
  -h, --help                       help for init
      --kube-config string         Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string    Use this key to download and use the required KubeEdge version
      --master string              Use this key to set K8s master address, eg: http://127.0.0.1:8080
      --tarballpath string         Use this key to set the temp directory path for KubeEdge tarball, if not exist, download it

F1229 00:21:03.111025    9172 keadm.go:27] not able to create /var/log/kubeedge/ folder path
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000130001, 0xc000710000, 0x5d, 0xb1)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2c9b220, 0xc000000003, 0x0, 0x0, 0xc000169880, 0x29bb6a6, 0x8, 0x1b, 0x1e41500)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printDepth(0x2c9b220, 0xc000000003, 0x0, 0x0, 0x1, 0xc0007c3f68, 0x1, 0x1)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:718 +0x165
k8s.io/klog/v2.(*loggingT).print(...)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:703
k8s.io/klog/v2.Fatal(...)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1436
main.main()
        /data/gopath/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0xa5

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x2c9b220)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x7f2cfc46f9c8, 0x72, 0x1e447a0)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0004dab18, 0x72, 0x1e44700, 0x2c1e290, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004dab00, 0xc00061e000, 0x8d2, 0x8d2, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0004dab00, 0xc00061e000, 0x8d2, 0x8d2, 0x203000, 0x78e01b, 0xc0003c72e0)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000305598, 0xc00061e000, 0x8d2, 0x8d2, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000569f60, 0xc00061e000, 0x8d2, 0x8d2, 0x121, 0x8cd, 0xc0006b1710)
        /usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc0003c7400, 0x1e41320, 0xc000569f60, 0x419265, 0x1a41da0, 0x1bbcde0)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc0003c7180, 0x1e42fc0, 0xc000305598, 0x5, 0xc000305598, 0x110)
        /usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0003c7180, 0x0, 0x0, 0xc0006b1d18)
        /usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc0003c7180, 0xc000651000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc000608f00, 0xc0001e83b8, 0x9, 0x9, 0xc0006b1d18, 0x1d05c00, 0x93b3ab)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1e41180, 0xc000608f00, 0xc0001e83b8, 0x9, 0x9, 0x9, 0xc000112030, 0x0, 0x1e41560)
        /usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc0001e83b8, 0x9, 0x9, 0x1e41180, 0xc000608f00, 0x0, 0x0, 0xc0000e9590, 0x0)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001e8380, 0xc0000e9590, 0x0, 0x0, 0x0)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0006b1fa8, 0x0, 0x0)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1794 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000107380)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1716 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:695 +0x66e

```
**Anything else we need to know?**:
#### the path '/var/log/kubeedge/ ' does not exist exist. even if i use `sudo mkdir /var/log/kubeedge/` to create the path first, but `sudo keadm init` still dones't work .

**Environment**:
<details><summary>Kubernets Version v1.20.1</summary>

```console
$ kubectl --version
# Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
# Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by daixiang0** [comment]
Check `/etc/kubeedge/` exists, it is abnormal for root failed to create dirs.

**Comment by echo467** [comment]
> Check `/etc/kubeedge/` exists, it is abnormal for root failed to create dirs.

ye, you are absolutely right, thank you very much
