### ISSUE TITLE
modbus mapper pod error-Cannot read property 'findIndex' of undefined

### ISSUE THREAD

**Issue by beyondyinjl2** [kubeedge/kubeedge#2513]
cd $GOPATH/src/github.com/kubeedge/kubeedge/mappers/modbus_mapper
kubectl create -f deployment.yaml

kubectl get pods -o wide
kubectl logs modbus-device-mapper-deployment-5455df7df4-5sjbp

CONNECTOR_DPL_NAME=dpl/deviceProfile.json
CONNECTOR_MQTT_IP=127.0.0.1
CONNECTOR_MQTT_PORT=1883
[2021-01-08T21:44:47.617] [INFO] appenders - start to watch dpl config
[2021-01-08T21:44:47.623] [INFO] appenders - start to check devicetwin state
/opt/src/watchfile.js:103
    let foundVisitor = dplConfigs.propertyVisitors.findIndex((element)=>{
                                                   ^

TypeError: Cannot read property 'findIndex' of undefined
    at buildVisitorMaps (/opt/src/watchfile.js:103:52)
    at processData (/opt/src/watchfile.js:73:13)
    at /opt/src/watchfile.js:45:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

**Comment by sailorvii** [comment]
The Modbus mapper doesn't fit the latest version. Version 1.3 and before could work. You could use the Modbus-go mapper.
