### ISSUE TITLE
Flaky test: github.com/kubeedge/kubeedge/edge/pkg/edgehub/config

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#269]
**Which jobs are failing**:
```
2019/03/19 04:52:10 WARN: empty configurtion from [CommandlineSource]
2019/03/19 04:52:10 WARN: empty configurtion from [MemorySource]
New file source added for configuration: /home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/conf/edge.yamlNew file source added for configuration: /home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/conf/logging.yamlNew file source added for configuration: /home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/conf/modules.yaml/home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/conf/logging.yamllogConfig:&{DEBUG  [stdout] true false  }
2019-03-19 04:52:10.858 +00:00 DEBUG :0 init logger...
2019-03-19 04:52:10.859 +00:00 INFO config/config.go:167 websocket connection header is map[]
2019-03-19 04:52:10.860 +00:00 INFO config/config.go:167 websocket connection header is map[]
2019-03-19 04:52:10.860 +00:00 WARN config/config.go:92 Failed to get write-deadline for web socket client: key does not exist
2019-03-19 04:52:10.860 +00:00 WARN config/config.go:99 Failed to get read-deadline for web socket client: key does not exist
2019-03-19 04:52:10.860 +00:00 WARN config/config.go:106 Failed to get handshake-timeout for web socket client: key does not exist
2019-03-19 04:52:10.860 +00:00 INFO config/config.go:167 websocket connection header is map[]
2019-03-19 04:52:10.860 +00:00 WARN config/config.go:119 Failed to get heartbeat for controller client: key does not exist
2019-03-19 04:52:10.860 +00:00 WARN config/config.go:126 Failed to get refresh-ak-sk-interval for controller client: key does not exist
2019-03-19 04:52:10.860 +00:00 WARN config/config.go:151 Failed to get auth info : key does not exist
2019-03-19 04:52:10.860 +00:00 INFO config/config.go:167 websocket connection header is map[]
2019-03-19 04:52:10.861 +00:00 WARN config/config.go:92 Failed to get write-deadline for web socket client: key does not exist
2019-03-19 04:52:10.861 +00:00 WARN config/config.go:99 Failed to get read-deadline for web socket client: key does not exist
2019-03-19 04:52:10.861 +00:00 WARN config/config.go:106 Failed to get handshake-timeout for web socket client: key does not exist
2019-03-19 04:52:10.861 +00:00 INFO config/config.go:167 websocket connection header is map[]
2019/03/19 04:52:10 DEBUG: EventReceived [%!s(*core.Event=&{FileSource CREATE edgehub.controller.cloud-hub-url })]
2019/03/19 04:52:10 DEBUG: EventReceived [%!s(*core.Event=&{FileSource CREATE edgehub.websocket.certfile /tmp/edge.crt})]
2019/03/19 04:52:10 DEBUG: EventReceived [%!s(*core.Event=&{FileSource CREATE edgehub.websocket.keyfile /tmp/edge.key})]
2019/03/19 04:52:10 DEBUG: EventReceived [%!s(*core.Event=&{FileSource CREATE edgehub.websocket.handshake-timeout 500})]
2019/03/19 04:52:10 DEBUG: EventReceived [%!s(*core.Event=&{FileSource CREATE edgehub.websocket.read-deadline 100})]
2019/03/19 04:52:10 DEBUG: EventReceived [%!s(*core.Event=&{FileSource CREATE edgehub.websocket.write-deadline 100})]
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData/edge.yaml REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData/edge.yaml": REMOVE], continue
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019-03-19 04:52:10.862 +00:00 ERROR config/config.go:74 Failed to get url for web socket client: key does not exist
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
2019-03-19 04:52:10.862 +00:00 INFO config/config.go:167 websocket connection header is map[]
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
2019/03/19 04:52:10 DEBUG: watch file error:%!(EXTRA []interface {}=[<nil>])
2019/03/19 04:52:10 DEBUG: watch file error:%!(EXTRA []interface {}=[<nil>])
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData/edge.yaml REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData/edge.yaml": REMOVE], continue
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData/edge.yaml REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData/edge.yaml": REMOVE], continue
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
2019/03/19 04:52:10 DEBUG: watch file error:%!(EXTRA []interface {}=[<nil>])
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData/edge.yaml REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData/edge.yaml": REMOVE], continue
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
2019/03/19 04:52:10 DEBUG: watch file error:%!(EXTRA []interface {}=[<nil>])
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
2019/03/19 04:52:10 DEBUG: watch file error:%!(EXTRA []interface {}=[<nil>])
2019-03-19 04:52:10.868 +00:00 WARN config/config.go:119 Failed to get heartbeat for controller client: key does not exist
2019-03-19 04:52:10.868 +00:00 WARN config/config.go:126 Failed to get refresh-ak-sk-interval for controller client: key does not exist
2019-03-19 04:52:10.868 +00:00 WARN config/config.go:151 Failed to get auth info : key does not exist
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
2019/03/19 04:52:10 DEBUG: watch file error:%!(EXTRA []interface {}=[<nil>])
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData/edge.yaml REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData/edge.yaml": REMOVE], continue
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x73f8d3]
goroutine 83 [running]:
github.com/kubeedge/kubeedge/vendor/github.com/ServiceComb/go-archaius/sources/file-source.(*watch).startWatchPool(0xc0003729c0)
	/home/travis/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/ServiceComb/go-archaius/sources/file-source/yamlconfigurationsource.go:384 +0x73
created by github.com/kubeedge/kubeedge/vendor/github.com/ServiceComb/go-archaius/sources/file-source.(*yamlConfigurationSource).DynamicConfigHandler
	/home/travis/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/ServiceComb/go-archaius/sources/file-source/yamlconfigurationsource.go:361 +0x91
FAIL	github.com/kubeedge/kubeedge/edge/pkg/edgehub/config	0.019s
```

**Which test(s) are failing**:

**Since when has it been failing**:

**Reason for failure**:

**Anything else we need to know**:

**Comment by m1093782566** [comment]
cc @rohitsardesai83

**Comment by sids-b** [comment]
cc @sujithsimon22 . I guess this test file is owned by Sujith.

**Comment by sujithsimon22** [comment]
@sids-b @m1093782566 I think this issue is a duplicate one. Pls refer to issue #263

**Comment by rohitsardesai83** [comment]
dup of #263
