### ISSUE TITLE
kubeedge v1.7.0 install error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by EnfangCui** [kubeedge/kubeedge#3030]
I tried  ./keadm init --kubeedge-version=1.7.0 --advertise-address="139.198.190.221"
The results are as follows, it seems succeed.
```
Kubernetes version verification passed, KubeEdge installation will start...
W0813 09:24:01.051245    4656 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0813 09:24:01.058744    4656 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0813 09:24:01.063517    4656 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0813 09:24:01.067824    4656 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Expected or Default KubeEdge version 1.7.0 is already downloaded and will checksum for it.
kubeedge-v1.7.0-linux-amd64.tar.gz checksum:
checksum_kubeedge-v1.7.0-linux-amd64.tar.gz.txt content:
Expected or Default KubeEdge version 1.7.0 is already downloaded
[Run as service] service file already exisits in /etc/kubeedge//cloudcore.service, skip download
kubeedge-v1.7.0-linux-amd64/
kubeedge-v1.7.0-linux-amd64/edge/
kubeedge-v1.7.0-linux-amd64/edge/edgecore
kubeedge-v1.7.0-linux-amd64/cloud/
kubeedge-v1.7.0-linux-amd64/cloud/csidriver/
kubeedge-v1.7.0-linux-amd64/cloud/csidriver/csidriver
kubeedge-v1.7.0-linux-amd64/cloud/admission/
kubeedge-v1.7.0-linux-amd64/cloud/admission/admission
kubeedge-v1.7.0-linux-amd64/cloud/cloudcore/
kubeedge-v1.7.0-linux-amd64/cloud/cloudcore/cloudcore
kubeedge-v1.7.0-linux-amd64/version

KubeEdge cloudcore is running, For logs visit:  /var/log/kubeedge/cloudcore.log
CloudCore started

```
But when I open   /var/log/kubeedge/cloudcore.log, it shows a error: 

```
I0813 09:24:04.074027    4709 server.go:73] Version: v1.7.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15df708]

goroutine 1 [running]:
github.com/kubeedge/kubeedge/cloud/cmd/cloudcore/app.NewCloudCoreCommand.func1(0xc000457b80, 0x28be118, 0x0, 0x0)
        /root/codes/src/github.com/kubeedge/kubeedge/cloud/cmd/cloudcore/app/server.go:84 +0x2e8
github.com/spf13/cobra.(*Command).execute(0xc000457b80, 0xc00011a190, 0x0, 0x0, 0xc000457b80, 0xc00011a190)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000457b80, 0xc000110058, 0x0, 0x0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:887
main.main()
        /root/codes/src/github.com/kubeedge/kubeedge/cloud/cmd/cloudcore/cloudcore.go:16 +0x65
```

Actually it is failed. What should I do?

**Comment by EnfangCui** [comment]
This problem does not exist in version 1.7.1, so I changed to version 1.7.1. And this issue is closed.
