### ISSUE TITLE
edgecontroller panics when there is no configuration for cloudhub.ca, cloudhub.cert, cloudhub.key.

### ISSUE THREAD

**Issue by trilokgm** [kubeedge/kubeedge#319]
**What happened**:
edgecontroller crashes with missing configuration for cloudhub.ca, cloudhub.cert, cloudhub.key.

**What you expected to happen**:
Exit gracefully with missing configuration information.

**How to reproduce it (as minimally and precisely as possible)**:
Remove configuration for
  ca: /tmp/rootCA.crt
  cert: /tmp/edge.crt
  key: /tmp/edge.key
in controller.yaml.

**Anything else we need to know?**:
Also, need to remove the code in cloudhub.go:Start() for redundant code.

	// init filter
	pool := x509.NewCertPool()
	ok := pool.AppendCertsFromPEM(util.HubConfig.Ca)
	if !ok {
		panic(fmt.Errorf("fail to load ca content"))
	}

**Environment**:
- KubeEdge version: 0.2
- Hardware configuration: Virtual box vm - 2 vcpus / 2GB memory
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`):Linux 4.18.0-16-generic 
- Others:

Logs==>

2019/04/04 13:30:25 WARN: empty configurtion from [CommandlineSource]
2019/04/04 13:30:25 WARN: empty configurtion from [MemorySource]
New file source added for configuration: /opt/spire/app-binaries/conf/controller.yamlNew file source added for configuration: /opt/spire/app-binaries/conf/edge.yamlNew file source added for configuration: /opt/spire/app-binaries/conf/logging.yamlNew file source added for configuration: /opt/spire/app-binaries/conf/modules.yaml/opt/spire/app-binaries/conf/logging.yamllogConfig:&{INFO edgecontroller.log [file stdout] true false  }
2019/04/04 13:30:25 RollingPolicy is empty, use default policy[size]
2019-04-04 13:30:25.959 +05:30 INFO core/module.go:41 module cloudhub registered
2019-04-04 13:30:25.981 +05:30 INFO config/buffer.go:27 update pod status buffer: 1024
2019-04-04 13:30:25.981 +05:30 INFO config/buffer.go:34 Update node status buffer: 1024
2019-04-04 13:30:25.981 +05:30 INFO config/buffer.go:41 query config map buffer: 1024
2019-04-04 13:30:25.981 +05:30 INFO config/buffer.go:48 query secret buffer: 1024
2019-04-04 13:30:25.981 +05:30 INFO config/context.go:28  send module name: cloudhub
2019-04-04 13:30:25.981 +05:30 INFO config/context.go:35 receive module name: controller
2019-04-04 13:30:25.981 +05:30 INFO config/context.go:42 response module name: cloudhub
2019-04-04 13:30:25.981 +05:30 INFO config/kube.go:38 kube master: http://localhost:8080
2019-04-04 13:30:25.981 +05:30 INFO config/kube.go:45 kube config: 
2019-04-04 13:30:25.981 +05:30 INFO config/kube.go:52 kube namespace: 
2019-04-04 13:30:25.981 +05:30 INFO config/kube.go:59 kube content type: application/vnd.kubernetes.protobuf
2019-04-04 13:30:25.981 +05:30 INFO config/kube.go:66 kube QPS: 5.000000
2019-04-04 13:30:25.981 +05:30 INFO config/kube.go:73 kube burst: 10
2019-04-04 13:30:25.982 +05:30 INFO config/kube.go:80 kube update frequency: 10s
2019-04-04 13:30:25.982 +05:30 INFO config/load.go:27 update pod status workers: 1
2019-04-04 13:30:25.982 +05:30 INFO config/load.go:34 update node status workers: 1
2019-04-04 13:30:25.982 +05:30 INFO config/load.go:41 query config map workers: 4
2019-04-04 13:30:25.982 +05:30 INFO config/load.go:48 query secret workers: 4
2019-04-04 13:30:25.982 +05:30 INFO config/messagelayer.go:18 message layer: context
2019-04-04 13:30:26.020 +05:30 INFO core/module.go:41 module controller registered
2019-04-04 13:30:26.021 +05:30 INFO core/core.go:23 starting module cloudhub
panic: interface conversion: interface {} is nil, not string

goroutine 9 [running]:
github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub.(*cloudHub).Start(0xc0000b4130, 0xc00030aca0)
	/home/root1/gopath/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub/cloudhub.go:39 +0x4fd
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.StartModules
	/home/root1/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:22 +0x153

**Comment by sids-b** [comment]
@trilokgm, we have added panic whenever we have missing compulsory configurations. Do we need to make this change in all places where we are panicking ?
@m1093782566 thoughts ?

**Comment by trilokgm** [comment]
@sids-b, the panic seen here is not an explicit added code. The panic occurs on the interface object when there is no configuration set on the config key.

util.HubConfig.Ca, err = ioutil.ReadFile(caI.(string))

Were you able to reproduce the problem and trace it?

**Comment by m1093782566** [comment]
@trilokgm I think it's a reasonable issue and would you please help this out?

**Comment by trilokgm** [comment]
Also, another suggestion would be to use defaults for missing configuration, if possible. If it is related to some files, then an appropriate error and list of defaulted configurations would help.

**Comment by sids-b** [comment]
I think think can help solve the issue
```go
caI, err := config.CONFIG.GetValue("cloudhub.ca").ToString()
// check error and if not nil return

util.HubConfig.Ca, err = ioutil.ReadFile(caI)
```

**Comment by sids-b** [comment]
Needs to be applied to all similar places wherever applicable.

**Comment by trilokgm** [comment]
@m1093782566 , I will be able to help fix this issue. can you please assign to me ? Thanks.

**Comment by m1093782566** [comment]
Sure, assigned it to you.
