### ISSUE TITLE
can not update device message from cloudcore to edgecore

### ISSUE THREAD

**Issue by dafanshu** [kubeedge/kubeedge#4110]
**What happened**:
`8月 11 13:38:43  edgecore[2454]: I0811 13:38:43.994083    2454 process.go:283] DeviceTwin receive msg
8月 11 13:38:43  edgecore[2454]: I0811 13:38:43.994650    2454 process.go:66] Send msg to the MemModule module in twin
8月 11 13:38:43  edgecore[2454]: I0811 13:38:43.994699    2454 membership.go:120] Membership event
8月 11 13:38:43  edgecore[2454]: I0811 13:38:43.995184    2454 membership.go:167] Add devices to edge group
8月 11 13:38:43  edgecore[2454]: E0811 13:38:43.997993    2454 imitator.go:89] failed to access database:sql: transaction has already been committed or rolled back
8月 11 13:38:43  edgecore[2454]: E0811 13:38:43.998053    2454 imitator.go:89] failed to access database:sql: transaction has already been committed or rolled back
8月 11 13:38:43  edgecore[2454]: E0811 13:38:43.998077    2454 imitator.go:89] failed to access database:sql: transaction has already been committed or rolled back
8月 11 13:38:44  edgecore[2454]: panic: failed to access database after 3 times try
8月 11 13:38:44  edgecore[2454]: goroutine 162 [running]:
8月 11 13:38:44  edgecore[2454]: k8s.io/apimachinery/pkg/util/runtime.Must(...)
8月 11 13:38:44  edgecore[2454]:         /root/kubeedge/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
8月 11 13:38:44  edgecore[2454]: github.com/kubeedge/kubeedge/edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator.(*imitator).Inject(0xc0004aa600, 0xc000cd8ea0, 0x24, 0x0, 0x0, 0x1828b69826c, 0xc000a58630, 0x8, 0x0, 0x0, ...)
8月 11 13:38:44  edgecore[2454]:         /root/kubeedge/edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go:48 +0x49e
8月 11 13:38:44  edgecore[2454]: github.com/kubeedge/kubeedge/edge/pkg/metamanager.(*metaManager).processUpdate(0xc000a582bd, 0xc000cd8ea0, 0x24, 0x0, 0x0, 0x1828b69826c, 0xc000a58630, 0x8, 0x0, 0x0, ...)
8月 11 13:38:44  edgecore[2454]:         /root/kubeedge/edge/pkg/metamanager/process.go:149 +0x2f5
8月 11 13:38:44  edgecore[2454]: github.com/kubeedge/kubeedge/edge/pkg/metamanager.(*metaManager).process(0xc000a582bd, 0xc000cd8ea0, 0x24, 0x0, 0x0, 0x1828b69826c, 0xc000a58630, 0x8, 0x0, 0x0, ...)
8月 11 13:38:44  edgecore[2454]:         /root/kubeedge/edge/pkg/metamanager/process.go:436 +0x305
8月 11 13:38:44  edgecore[2454]: github.com/kubeedge/kubeedge/edge/pkg/metamanager.(*metaManager).runMetaManager.func1(0xc000a582bd)
8月 11 13:38:44  edgecore[2454]:         /root/kubeedge/edge/pkg/metamanager/process.go:476 +0x3f8
8月 11 13:38:44  edgecore[2454]: created by github.com/kubeedge/kubeedge/edge/pkg/metamanager.(*metaManager).runMetaManager
8月 11 13:38:44  edgecore[2454]:         /root/kubeedge/edge/pkg/metamanager/process.go:462 +0x3f
8月 11 13:38:44  systemd[1]: edgecore.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.9.2
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by RyanZhaoXB** [comment]
thanks for reporting this bug.  the error is "failed to access database:sql: transaction has already been committed or rolled back "
we have found this bug and we are fixing it in this pr https://github.com/kubeedge/kubeedge/pull/4119
