### ISSUE TITLE
hollow-edge-node couldn't work for edgemark

### ISSUE THREAD

**Issue by univwang** [kubeedge/kubeedge#4601]
**What happened**:
when "kubectl create -f hollow-edge-node_template.yaml", i failed

```
[root@master ~]# kubectl logs hollow-edge-node-bdbb9f4f7-mp4cv -n emns
edgemark flag redefined: version
panic: edgemark flag redefined: version

goroutine 1 [running]:
github.com/kubeedge/kubeedge/vendor/github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000138000, 0xc000487540)
        /go/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/pflag/flag.go:848 +0x825
github.com/kubeedge/kubeedge/vendor/github.com/spf13/pflag.(*FlagSet).VarPF(0xc000138000, 0x33b1468, 0xc0002da7e0, 0x2efb247, 0x7, 0x0, 0x0, 0x2f45cd1, 0x22, 0x1)
        /go/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/pflag/flag.go:831 +0x10b
github.com/kubeedge/kubeedge/vendor/github.com/spf13/pflag.(*FlagSet).VarP(...)
        /go/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/pflag/flag.go:837
github.com/kubeedge/kubeedge/vendor/github.com/spf13/pflag.Var(...)
        /go/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/pflag/flag.go:899
github.com/kubeedge/kubeedge/pkg/version/verflag.VersionVar(0xc0002da7e0, 0x2efb247, 0x7, 0x0, 0x2f45cd1, 0x22)
        /go/src/github.com/kubeedge/kubeedge/pkg/version/verflag/verflag.go:77 +0x89
github.com/kubeedge/kubeedge/pkg/version/verflag.Version(...)
        /go/src/github.com/kubeedge/kubeedge/pkg/version/verflag/verflag.go:84
github.com/kubeedge/kubeedge/pkg/version/verflag.init()
        /go/src/github.com/kubeedge/kubeedge/pkg/version/verflag/verflag.go:91 +0x77
```

**Anything else we need to know?**:
I used two clusters, one with only master node and the other with master and work nodes. Use "docker pull kubedge/edge: v1.12.1" to pull the image,

**Environment**:
- Kubernetes version (use `kubectl version`): client v1.22.4 and server v1.22.17
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):v1.12.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`): PRETTY_NAME="CentOS Linux 7 (Core)"
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by univwang** [comment]
I used v1.13.0 and deleted the "-- - alsogtostderr ans -- -v=2" in "hollow_edge_node_template. yaml"
However, there was a problem with the time zone. Later, I set the time manually and successfully added the hollow node to edgemark cluster. But I don't know whether it will have a bad effect in the future.
