### ISSUE TITLE
edgecore exits with status=2/INVALIDARGUMENT on rasberry pi 3 model B+ ( version 1.13.0 )

### ISSUE THREAD

**Issue by tzagkaris** [kubeedge/kubeedge#4760]
Hi, I'm trying to join a rasberry pi on a minikube cluster for demo purposes. I'm not that experienced with kubeedge so I label this as a question as it may not be a bug.

**What happened and what you expected to happen**:
Edgecore ( from keadm ) exits with the following error:
 
```
$ journalctl -u edgecore.service -xe
tnk116 edgecore[14987]: goroutine 287 [running]:
tnk116 edgecore[14987]: runtime/internal/atomic.panicUnaligned()
tnk116 edgecore[14987]:         /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
tnk116 edgecore[14987]: runtime/internal/atomic.Load64(0x5bb9f6c)
tnk116 edgecore[14987]:         /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:286 +0x14
tnk116 edgecore[14987]: github.com/google/cadvisor/manager.(*containerData).updateStats(0x5bb9e00)
tnk116 edgecore[14987]:         /work/vendor/github.com/google/cadvisor/manager/container.go:676 +0x43c
tnk116 edgecore[14987]: github.com/google/cadvisor/manager.(*containerData).housekeepingTick(0x5bb9e00, 0x5ac3180, 0x5f5e100)
tnk116 edgecore[14987]:         /work/vendor/github.com/google/cadvisor/manager/container.go:587 +0x104
tnk116 edgecore[14987]: github.com/google/cadvisor/manager.(*containerData).housekeeping(0x5bb9e00)
tnk116 edgecore[14987]:         /work/vendor/github.com/google/cadvisor/manager/container.go:535 +0x3bc
tnk116 edgecore[14987]: created by github.com/google/cadvisor/manager.(*containerData).Start
tnk116 edgecore[14987]:         /work/vendor/github.com/google/cadvisor/manager/container.go:122 +0x2c
tnk116 systemd[1]: edgecore.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
I understand that this is probably related to architecture mismatch. Don't really know what I am doing wrong. keadm-v1.13.0-linux-arm was downloaded from releases.  

**How to reproduce it (as minimally and precisely as possible)**:
Run 
`sudo keadm join --runtimetype=docker --cloudcore-ipport=<minikube ip>:10000 --token=<token> --kubeedge-version=1.13.0`

**Anything else we need to know?**:
- Changed cgroup driver to cgroupfs as suggested.
- Changed runtimetype to docker as suggested.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-15T02:14:53Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.13.0

**Comment by wackxu** [comment]
This is a cadvisor issue, the oomEvents's struct is not aligned in 32-byte,  we need upgrade the version for cadvisor
see https://github.com/google/cadvisor/pull/3029/files

**Comment by wackxu** [comment]
https://github.com/kubernetes/kubernetes/pull/109029 has fix the bug, cc @Shelley-BaoYue could we update the cadvisor version in our kubernetes branch

**Comment by wu9007** [comment]
In version 1.13.2 of Kubeedge, is Raspberry PI available for edge nodes?

**Comment by wu9007** [comment]
@wackxu Will the edge node of Kubeedge 1.13.2 be able to use Raspberry PI?

**Comment by Shelley-BaoYue** [comment]
@wu9007  KubeEdge 1.14 has upgrade Kubernetes dependency version to 1.24, may be able to use Raspberry PI
