### ISSUE TITLE
keadm init: "Error: the server could not find the requested resource"

### ISSUE THREAD

**Issue by Albertchamberlain** [kubeedge/kubeedge#4795]
**What happened**:
keadm init --advertise-address=192.168.200.128 --kubeedge-version=1.13.0
**What you expected to happen**:
KubeEdge cloudcore is running, For logs visit:  /var/log/kubeedge/cloudcore.log
CloudCore started
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:50:27Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
If success，The version is 1.13.0
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
  - Kernel (e.g. `uname -a`):Linux master 3.10.0-1160.90.1.el7.x86_64  SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
  - Go version (e.g. `go version`):go version go1.12.9 linux/amd64
  - Others:

[root@master kubeedge]# keadm init --advertise-address=192.168.200.128 --kubeedge-version=1.13.0
Kubernetes version verification passed, KubeEdge installation will start...
Error: the server could not find the requested resource
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.5.0  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver

Flags:
      --advertise-address string   Use this key to set IPs in cloudcore's certificate SubAltNames field. eg: 10.10.102.78,10.10.102.79
      --domainname string          Use this key to set domain names in cloudcore's certificate SubAltNames field. eg: www.cloudcore.cn,www.kubeedge.cn
  -h, --help                       help for init
      --kube-config string         Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string    Use this key to download and use the required KubeEdge version
      --master string              Use this key to set K8s master address, eg: http://127.0.0.1:8080
      --tarballpath string         Use this key to set the temp directory path for KubeEdge tarball, if not exist, download it

F0528 16:32:06.302315   15480 keadm.go:27] the server could not find the requested resource
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc00066a0b0, 0x5c, 0xb0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2c96440, 0xc000000003, 0x0, 0x0, 0xc000474380, 0x29b3ad1, 0x8, 0x1b, 0x1e3a500)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printDepth(0x2c96440, 0xc000000003, 0x0, 0x0, 0x1, 0xc000919f68, 0x1, 0x1)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:718 +0x165
k8s.io/klog/v2.(*loggingT).print(...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:703
k8s.io/klog/v2.Fatal(...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1436
main.main()
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0xa5

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x2c96440)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 23 [runnable]:
text/template/parse.(*lexer).emit(...)
        /root/.gvm/gos/go1.15/src/text/template/parse/lex.go:157
text/template/parse.lexText(0xc0005a6a20, 0x1cfdfd8)
        /root/.gvm/gos/go1.15/src/text/template/parse/lex.go:269 +0x512
text/template/parse.(*lexer).run(0xc0005a6a20)
        /root/.gvm/gos/go1.15/src/text/template/parse/lex.go:230 +0x37
created by text/template/parse.lex
        /root/.gvm/gos/go1.15/src/text/template/parse/lex.go:223 +0x190

goroutine 22 [runnable]:
golang.org/x/net/http2.(*clientStream).awaitRequestCancel(0xc0002ff600, 0xc0005c2e00)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:343
created by golang.org/x/net/http2.(*clientConnReadLoop).handleResponse
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:2054 +0x768

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7f6a78e099d8, 0x72, 0x1e3c4a0)
        /root/.gvm/gos/go1.15/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0004a7998, 0x72, 0xc00053a000, 0x8da, 0x8da)
        /root/.gvm/gos/go1.15/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /root/.gvm/gos/go1.15/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004a7980, 0xc00053a000, 0x8da, 0x8da, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.15/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc0004a7980, 0xc00053a000, 0x8da, 0x8da, 0x203000, 0x78b1db, 0xc0000bdd60)
        /root/.gvm/gos/go1.15/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00059a970, 0xc00053a000, 0x8da, 0x8da, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.15/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0005c8120, 0xc00053a000, 0x8da, 0x8da, 0x1e, 0x791, 0xc0008bd710)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc0000bde80, 0x1e39020, 0xc0005c8120, 0x416ea5, 0x1a38f80, 0x1bb4200)
        /root/.gvm/gos/go1.15/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc0000bdc00, 0x1e3acc0, 0xc00059a970, 0x5, 0xc00059a970, 0xd)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0000bdc00, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc0000bdc00, 0xc000654000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0003b28a0, 0xc000776738, 0x9, 0x9, 0xc000654009, 0x2c97380, 0x7f6aa22fb108)
        /root/.gvm/gos/go1.15/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1e38e80, 0xc0003b28a0, 0xc000776738, 0x9, 0x9, 0x9, 0xc0008bdd38, 0x92773c, 0x1af2f60)
        /root/.gvm/gos/go1.15/src/io/io.go:314 +0x87
io.ReadFull(...)
        /root/.gvm/gos/go1.15/src/io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc000776738, 0x9, 0x9, 0x1e38e80, 0xc0003b28a0, 0x0, 0x0, 0xc0008bddd0, 0xc0004d6350)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000776700, 0xc0004bc080, 0x0, 0x0, 0x0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0008bdfa8, 0x0, 0x0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0004d6300)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5
[root@master kubeedge]# keadm init --advertise-address="192.168.200.128" --kubeedge-version="v1.13.0"
panic: semver: Parse(v1.13.0): Invalid character(s) found in major number "v1"

goroutine 1 [running]:
github.com/blang/semver.MustParse(0x7fff573c0772, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/blang/semver/semver.go:319 +0x1c5
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/cloud.Add2ToolsList(0xc000098570, 0xc0000985a0, 0xc00032d8c0, 0x1c2c809, 0x4)
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/cloud/init.go:135 +0x186
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/cloud.NewCloudInit.func1(0xc0000f0580, 0xc00000fb40, 0x0, 0x2, 0x0, 0x0)
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/cloud/init.go:68 +0x9f
github.com/spf13/cobra.(*Command).execute(0xc0000f0580, 0xc00000fb20, 0x2, 0x2, 0xc0000f0580, 0xc00000fb20)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f02c0, 0xc00012c000, 0x1e3afa0, 0xc00012c008)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:887
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app.Run(0x2c2d860, 0xc000000180)
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/keadm.go:33 +0x93
main.main()
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:26 +0x26
[root@master kubeedge]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:50:27Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
[root@master kubeedge]# cloudcore --version
bash: cloudcore: command not found...
[root@master kubeedge]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@master kubeedge]# uname -a
Linux master 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@master kubeedge]# go version
go version go1.12.9 linux/amd64
[root@master kubeedge]# keadm init --advertise-address="192.168.200.128" --kubeedge-version="v1.13.0"
panic: semver: Parse(v1.13.0): Invalid character(s) found in major number "v1"

goroutine 1 [running]:
github.com/blang/semver.MustParse(0x7ffebc62d772, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/blang/semver/semver.go:319 +0x1c5
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/cloud.Add2ToolsList(0xc0003f2360, 0xc0003f2390, 0xc00012f080, 0x1c2c809, 0x4)
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/cloud/init.go:135 +0x186
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/cloud.NewCloudInit.func1(0xc000230dc0, 0xc0003ff300, 0x0, 0x2, 0x0, 0x0)
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/cloud/init.go:68 +0x9f
github.com/spf13/cobra.(*Command).execute(0xc000230dc0, 0xc0003ff2c0, 0x2, 0x2, 0xc000230dc0, 0xc0003ff2c0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000230b00, 0xc00012c000, 0x1e3afa0, 0xc00012c008)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:887
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app.Run(0x2c2d860, 0xc000000180)
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/keadm.go:33 +0x93
main.main()
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:26 +0x26

Thank You！😀

**Comment by Albertchamberlain** [comment]
![image](https://github.com/kubeedge/kubeedge/assets/47343901/c98e6c5b-7560-47b4-b9f5-63b53a7df338)

k8s：1.22.7
kubeedge：1.13.0

**Comment by Albertchamberlain** [comment]
keadm version：1.6.2
