### ISSUE TITLE
deploy edgecontroller into a k8s cluster, the pod status is not running

### ISSUE THREAD

**Issue by googlebabaio** [kubeedge/kubeedge#480]
## **What happened**:
deploy the cloud part(edgecontroller) into a k8s cluster
```
kubectl create -f 07-deployment.yaml 
```

and `deployment/edgecontroller` pod's status is `error` or `CrashLoopBackOff`

```
# kubectl delete -f 07-deployment.yaml
deployment.apps "edgecontroller" deleted
# kubectl create -f 07-deployment.yaml
deployment.apps/edgecontroller created

# kubectl get pod -n kubeedge
NAME                              READY   STATUS             RESTARTS   AGE
edgecontroller-6bd446b946-ppsb9   0/1     CrashLoopBackOff   7          14m
# 
# kubectl logs edgecontroller-6bd446b946-ppsb9 -n kubeedge
2019/05/09 02:09:08 WARN: empty configurtion from [CommandlineSource]
2019/05/09 02:09:08 WARN: empty configurtion from [MemorySource]
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yaml] value
New file source added for configuration: /etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/modules.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/controller.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/logging.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/modules.yaml/etc/kubeedge/cloud/conf/logging.yamllogConfig:&{INFO  [stdout] true false  }
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/modules.yaml] value
2019-05-09 02:09:08.094 +00:00 INFO core/module.go:41 module cloudhub registered
2019-05-09 02:09:08.096 +00:00 INFO config/buffer.go:27 update pod status buffer: 1024
2019-05-09 02:09:08.096 +00:00 INFO config/buffer.go:34 Update node status buffer: 1024
2019-05-09 02:09:08.096 +00:00 INFO config/buffer.go:41 query config map buffer: 1024
2019-05-09 02:09:08.096 +00:00 INFO config/buffer.go:48 query secret buffer: 1024
2019-05-09 02:09:08.096 +00:00 INFO config/context.go:28  send module name: cloudhub
2019-05-09 02:09:08.096 +00:00 INFO config/context.go:35 receive module name: controller
2019-05-09 02:09:08.096 +00:00 INFO config/context.go:42 response module name: cloudhub
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:38 kube master: https://kubernetes.default.svc.cluster.local:443
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:45 kube config: /etc/kubeedge/cloud/kubeconfig.yaml
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:52 kube namespace:
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:59 kube content type: application/vnd.kubernetes.protobuf
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:66 kube QPS: 5.000000
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:73 kube burst: 10
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:80 kube update frequency: 10s
2019-05-09 02:09:08.096 +00:00 INFO config/load.go:27 update pod status workers: 1
2019-05-09 02:09:08.096 +00:00 INFO config/load.go:34 update node status workers: 1
2019-05-09 02:09:08.096 +00:00 INFO config/load.go:41 query config map workers: 4
2019-05-09 02:09:08.096 +00:00 INFO config/load.go:48 query secret workers: 4
2019-05-09 02:09:08.096 +00:00 INFO config/messagelayer.go:18 message layer: context
2019-05-09 02:09:08.102 +00:00 INFO core/module.go:41 module controller registered
2019-05-09 02:09:08.102 +00:00 INFO core/core.go:23 starting module cloudhub
2019-05-09 02:09:08.102 +00:00 INFO core/core.go:23 starting module controller
panic: open /etc/kubeedge/ca/ca.crt: no such file or directory

goroutine 11 [running]:
github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub.(*cloudHub).Start(0xc00000e168, 0xc00019bee0)
        /go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub/cloudhub.go:41 +0x544
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.StartModules
        /go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:22 +0x166
```

According to the error alert info, check the corresponding node also has ca. CRT and other related files.
```
# kubectl get pod -n kubeedge -owide
NAME                              READY   STATUS             RESTARTS   AGE   IP         NODE                 NOMINATED NODE   READINESS GATES
edgecontroller-7794f8bccf-5n9l5   0/1     CrashLoopBackOff   8          19m   10.1.1.9   host-192-168-3-124   <none>           <none>
#
# ssh -p 10022 192.168.3.124 tree /etc/kubeedge/
root@192.168.3.124's password:
/etc/kubeedge/
|-- ca
|   |-- ca.crt
|   |-- ca.key
|   `-- ca.srl
|-- certs
|   |-- cloud.crt
|   |-- cloud.csr
|   |-- cloud.key
|   |-- edge.crt
|   |-- edge.csr
|   `-- edge.key
`-- cloud
```

and master node also has ca. CRT and other related files.

### configmap:
```
# kubectl describe cm edgecontroller -n kubeedge
Name:         edgecontroller
Namespace:    kubeedge
Labels:       k8s-app=kubeedge
              kubeedge=edgecontroller
Annotations:  <none>

Data
====
controller.yaml:
----
controller:
  kube:
    master: https://kubernetes.default.svc.cluster.local:443
    kubeconfig: /etc/kubeedge/cloud/kubeconfig.yaml
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    node_update_frequency: 10
cloudhub:
  address: 0.0.0.0
  port: 10000
  ca: /etc/kubeedge/ca/ca.crt
  cert: /etc/kubeedge/certs/cloud.crt
  key: /etc/kubeedge/certs/cloud.key
  keepalive-interval: 30
  write-timeout: 30
  node-limit: 10

logging.yaml:
----
loggerLevel: "INFO"
enableRsyslog: false
logFormatText: true
writers: [stdout]

modules.yaml:
----
modules:
  enabled: [controller, cloudhub]

Events:  <none>
```

### secret
```
# kubectl describe secret edgecontroller -n kubeedge
Name:         edgecontroller
Namespace:    kubeedge
Labels:       k8s-app=kubeedge
              kubeedge=edgecontroller
Annotations:  <none>

Type:  Opaque

Data
====
ca.crt:     1976 bytes
cloud.crt:  1513 bytes
cloud.key:  1679 bytes
```

### deployment.yaml
```
# cat 07-deployment.yaml.bak
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: edgecontroller
  name: edgecontroller
  namespace: kubeedge
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: edgecontroller
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: edgecontroller
    spec:
      initContainers:
      - name: kubeconfig
        image: alpine:3.x
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeedge/cloud
          subPath: kubeconfig.yaml
        command:
        - /bin/sh
        - -c
        - |
          apk --no-cache add coreutils && cat | tee /etc/kubeedge/cloud/kubeconfig.yaml <<EOF
          apiVersion: v1
          kind: Config
          clusters:
          - name: kubeedge
            cluster:
              certificate-authority-data: $(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 -w 0)
          users:
          - name: kubeedge
            user:
              token: $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          contexts:
          - name: kubeedge
            context:
              cluster: kubeedge
              user: kubeedge
          current-context: kubeedge
          EOF
      containers:
      - name: edgecontroller
        image: edgecontroller:v0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10000
          name: cloudhub
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: conf
          mountPath: /etc/kubeedge/cloud/conf
        - name: certs
          mountPath: /etc/kubeedge/certs
        - name: kubeconfig
          mountPath: /etc/kubeedge/cloud
          subPath: kubeconfig.yaml
      restartPolicy: Always
      serviceAccount: edgecontroller
      serviceAccountName: edgecontroller
      volumes:
      - name: conf
        configMap:
          name: edgecontroller
      - name: certs
        secret:
          secretName: edgecontroller
      - name: kubeconfig
        emptyDir: {}
```

### image alpine:3.x 
Dockerfile
``` 
FROM alpine:3.9
RUN apk --no-cache add coreutils
```

### docker info on node host-192-168-3-124 
```
[root@host-192-168-3-124 cloud]# docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED              STATUS                          PORTS               NAMES
4717efabb652        e3ff3f3f385f                                "edgecontroller"         About a minute ago   Exited (2) About a minute ago                       k8s_edgecontroller_edgecontroller-6bd446b946-ppsb9_kubeedge_ea7d77b4-71fd-11e9-bf45-525400ddf27d_7
a7dfbac5529d        4904ef1d2b13                                "/bin/sh -c 'cat | t…"   12 minutes ago       Exited (0) 12 minutes ago                           k8s_kubeconfig_edgecontroller-6bd446b946-ppsb9_kubeedge_ea7d77b4-71fd-11e9-bf45-525400ddf27d_0

```

#### init container
```
[root@host-192-168-3-124 cloud]# docker logs a7dfbac5529d
apiVersion: v1
kind: Config
clusters:
- name: kubeedge
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EVXdPREV3TVRjek1sb1hEVEk1TURVd05URXdNVGN6TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTm5uCm5KR0FHcTArZVdYcUdIMEcrVmNxUnk2QjBSOVhRQlRjY1hDQVNVNHpwSk5wcSt6djBYNjV0UkdUVE0wNWh6TUoKcnNkNnhDcE5EaDR5WmR2Ym8zVXE0ay9wd1YrVmxxVmorZEZjM1BTUFZFb2l4OWZLanZkUUNEQzhqbW82aVJrRwp4V1hQSm5TdDhiVm44VTVqWTg2TDVLMTMwYVp4WHlkTTNmOWJzMlk1Mkdja1NWMkxIUUxrU3I2cGRmQmdmNy81CllDb3EweEVpV09UVE15UTZzd0FtazZBZC9zMHovc1NNZjFXMytiS1c0UmRsM3FFbFRvbjNIQVpuSkd2MHhLa2IKdnpQeXZROXpTMHFxWDZxWXljcTNva2FONjBIWk1EQzdFT1NxVFZJcFRVOWU5aVFLU1hGSUhqeGk5R2Y3N09JdgpHek5WSjRBS2VUMWtlR2s2WmpFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMWGJHV3U3VjFJd2Y0ajJHVUNNdXN5SmRpaFAKRGgwcnVoK01CdlpIYUZhWUNNVG92Vk9CUG5mRm5Od2JLSzJTTFYvNUt4UGp2RGNiMjhsbjJuaEhEVjRVTGtjUwpoREhxdDBNWVB1eW56OVk2eWo3QU1HU05HaWw1ZkMxL3oxZms5cTJnMzNaVlkwL1FxRXpJa0FOV2V6akt4dzJ2CmhkZFFNcHdheXpUK0s2RWdlcGRXeGV6eFAxLzVvQUpJcDJOVDJPUG9ObEdLMmtaZ1hpZjNLQzRTc2xoODF1Vi8KOE5Pa3pWanQ5UXJ5VHhqdUtBRnUxc1Zva1FMTnhKK1RpRGVxOXRaQnN2MWxSQmxMQ25oNUFzNjdnSCtaQWZhTwpDbTBqQzFENlJXMXA0QkFOdkFRYlRRcUpHWnA3VlIxYTk2LzBuL04vQmJ1THh2Z0tIZ3B0Tndob3Q4cz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
users:
- name: kubeedge
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlZWRnZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJlZGdlY29udHJvbGxlci10b2tlbi14cHJnYyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJlZGdlY29udHJvbGxlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImIyNzBlOGNmLTcxZjQtMTFlOS1iZjQ1LTUyNTQwMGRkZjI3ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlZWRnZTplZGdlY29udHJvbGxlciJ9.M1N_LRZkwT8keIcFzcevxdcMtzYsdXrWz0FbN5qZF3Wm44y0Bl8zPAy5CMxHPYi3opYfxa6x6GW3OMTYt2ep11PIEw41skF5XM_4vqIvUh3lJcYxa8FKtZnanNA13fuTasdI_HMHt-ATtWMjFY1VTxF5HO402oR14uREzsFfIHJ69V8rGgPpSOLmneKv8Jj_XxnXR7BFF9Qjo69yVDijeW22k958tiFVJrbUq6go7oJxIBH6rYlmWHDlMgV-jcoefyQUG2OG5V6bbMdJDglNxmZteUQAvltaNcWHF_3JSXmm1uO1R5FC3sH8Y1Wvs85n6kq6FQqej0zbPyzgEeufbg
contexts:
- name: kubeedge
  context:
    cluster: kubeedge
    user: kubeedge
current-context: kubeedge
```

#### container
```
[root@host-192-168-3-124 cloud]# docker logs 4717efabb652
2019/05/09 02:09:08 WARN: empty configurtion from [CommandlineSource]
2019/05/09 02:09:08 WARN: empty configurtion from [MemorySource]
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yaml] value
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yaml] value
New file source added for configuration: /etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/controller.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/logging.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/modules.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/controller.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/logging.yamlNew file source added for configuration: /etc/kubeedge/cloud/conf/modules.yaml/etc/kubeedge/cloud/conf/logging.yamllogConfig:&{INFO  [stdout] true false  }
2019/05/09 02:09:08 INFO: Two files have same priority. keeping [/etc/kubeedge/cloud/conf/..2019_05_09_01_58_18.293878334/modules.yaml] value
2019-05-09 02:09:08.094 +00:00 INFO core/module.go:41 module cloudhub registered
2019-05-09 02:09:08.096 +00:00 INFO config/buffer.go:27 update pod status buffer: 1024
2019-05-09 02:09:08.096 +00:00 INFO config/buffer.go:34 Update node status buffer: 1024
2019-05-09 02:09:08.096 +00:00 INFO config/buffer.go:41 query config map buffer: 1024
2019-05-09 02:09:08.096 +00:00 INFO config/buffer.go:48 query secret buffer: 1024
2019-05-09 02:09:08.096 +00:00 INFO config/context.go:28  send module name: cloudhub
2019-05-09 02:09:08.096 +00:00 INFO config/context.go:35 receive module name: controller
2019-05-09 02:09:08.096 +00:00 INFO config/context.go:42 response module name: cloudhub
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:38 kube master: https://kubernetes.default.svc.cluster.local:443
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:45 kube config: /etc/kubeedge/cloud/kubeconfig.yaml
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:52 kube namespace:
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:59 kube content type: application/vnd.kubernetes.protobuf
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:66 kube QPS: 5.000000
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:73 kube burst: 10
2019-05-09 02:09:08.096 +00:00 INFO config/kube.go:80 kube update frequency: 10s
2019-05-09 02:09:08.096 +00:00 INFO config/load.go:27 update pod status workers: 1
2019-05-09 02:09:08.096 +00:00 INFO config/load.go:34 update node status workers: 1
2019-05-09 02:09:08.096 +00:00 INFO config/load.go:41 query config map workers: 4
2019-05-09 02:09:08.096 +00:00 INFO config/load.go:48 query secret workers: 4
2019-05-09 02:09:08.096 +00:00 INFO config/messagelayer.go:18 message layer: context
2019-05-09 02:09:08.102 +00:00 INFO core/module.go:41 module controller registered
2019-05-09 02:09:08.102 +00:00 INFO core/core.go:23 starting module cloudhub
2019-05-09 02:09:08.102 +00:00 INFO core/core.go:23 starting module controller
panic: open /etc/kubeedge/ca/ca.crt: no such file or directory

goroutine 11 [running]:
github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub.(*cloudHub).Start(0xc00000e168, 0xc00019bee0)
        /go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub/cloudhub.go:41 +0x544
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.StartModules
        /go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:22 +0x166
```

## **Environment**:
- KubeEdge version: 0.2.1
- Kubernetes Version: 1.14.1 --using kubeadm
- Hardware configuration: 8C 16G
- OS (e.g. from /etc/os-release): centos7.5 
- Kernel (e.g. `uname -a`): 3.10.0-514.el7.x86_64
- Others:

**Comment by tedli** [comment]
I think the deployment not reads key and cert from host machine,  but from k8s  secret.  Have you create secret for the edgecontroller deployment?

**Comment by googlebabaio** [comment]
> I think the deployment not reads key and cert from host machine, but from k8s secret. Have you create secret for the edgecontroller deployment?

Thank you for pointing out.

I rewrote a nginx deployment to test it, the mounts are the same as the `07-deployment.yaml` one.
Find that it works OK! Then exec in `nginx`-pod , find `ca.crt`,`cloud.crt` and `cloud.key` are both in `/etc/kubeedge/certs`!

Finally I found out that I misunderstood it! 
The location of ca/cert/key in cloudhub from `05-configmap.yaml` actually tells pod which directory should be found in the container itself after booting, rather than the configuration path of the node host.

**Comment by googlebabaio** [comment]
I found out that I misunderstood it!
The location of ca/cert/key in cloudhub from `05-configmap.yaml` actually tells pod which directory should be found in the container itself after booting, rather than the configuration path of the node host.
