### ISSUE TITLE
request api/v1/nodes/{nodeHost}/proxy/metrics ,cloudCore/cloudStream panic

### ISSUE THREAD

**Issue by xiezg** [kubeedge/kubeedge#5005]
**What happened**:

 cloudCore panic:

I0911 15:23:35.452345       1 session.go:128] Add a new apiserver connection APIServer_MetricsConnection MessageID 80 in to Tunnel session [test-camerahelper-192.168.85.229]
I0911 15:23:35.463365       1 containermetrics_connection.go:121] APIServer_MetricsConnection MessageID 80 send close message to edge successfully
I0911 15:23:35.463389       1 containermetrics_connection.go:100] APIServer_MetricsConnection MessageID 80 end successful
I0911 15:23:35.465683       1 log.go:184] http: panic serving 192.168.85.229:56108: runtime error: invalid memory address or nil pointer dereference
goroutine 4274 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x1a9f700, 0x3143bc0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
bufio.(*Writer).Flush(0xc0027be680)
	/usr/local/go/src/bufio/bufio.go:607 +0x56
bufio.(*Writer).Write(0xc0027be680, {0xc0029be000, 0x7f959a814968, 0x0})
	/usr/local/go/src/bufio/bufio.go:643 +0xd8
net/http.(*response).write(0xc000222e00, 0x7f, {0xc0029be000, 0x7f, 0x200}, {0x0, 0x0})
	/usr/local/go/src/net/http/server.go:1593 +0x21e
net/http.(*response).Write(0x1, {0xc0029be000, 0x176fbd1, 0xc0005f0880})
	/usr/local/go/src/net/http/server.go:1551 +0x30
github.com/kubeedge/kubeedge/cloud/pkg/cloudstream.(*ContainerMetricsConnection).WriteToAPIServer(0x2, {0xc0029be000, 0x50, 0x7f95c160d5b8})
	/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudstream/containermetrics_connection.go:63 +0x27
github.com/kubeedge/kubeedge/cloud/pkg/cloudstream.(*Session).ProxyTunnelMessageToApiserver(0xc00342ae40, 0xc000e52810)
	/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudstream/session.go:102 +0x47c
github.com/kubeedge/kubeedge/cloud/pkg/cloudstream.(*Session).Serve(0xc00342ae40)
	/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudstream/session.go:81 +0xd3
github.com/kubeedge/kubeedge/cloud/pkg/cloudstream.(*TunnelServer).connect(0xc000384320, 0xc000cea510, 0x1fe5d00)
	/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudstream/tunnelserver.go:143 +0x65d
github.com/kubeedge/kubeedge/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc0004b6d80, {0x1fe5d00, 0xc00081c380}, 0xc0005df500)
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/emicklei/go-restful/container.go:285 +0x934
net/http.HandlerFunc.ServeHTTP(0x3b, {0x1fe5d00, 0xc00081c380}, 0x0)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc000b18b60, {0x1fe5d00, 0xc00081c380}, 0xc0005df500)
	/usr/local/go/src/net/http/server.go:2425 +0x149
github.com/kubeedge/kubeedge/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0x0, {0x1fe5d00, 0xc00081c380}, 0x468a0e)
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/emicklei/go-restful/container.go:300 +0x27
net/http.serverHandler.ServeHTTP({0xc000cea330}, {0x1fe5d00, 0xc00081c380}, 0xc0005df500)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000e3a3c0, {0x2008718, 0xc000e52ba0})
	/usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8
I0911 15:23:35.477080       1 tunnelserver.go:121] get a new tunnel agent hostname test-camerahelper-192.168.85.229, internalIP 172.16.25.10
E0911 15:23:37.885785       1 streamserver.go:177] Failed to get metrics, err: can not find test-camerahelper-192.168.85.228 session

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

terminal-1:
kubectl proxy --port 8002

terminal-2:
export nodeHost='test-camerahelper-192.168.85.229'
curl -m 0.010 http://127.0.0.1:8002/api/v1/nodes/${nodeHost}/proxy/metrics

**Anything else we need to know?**:

git commit: 1554bbd7381ae6ff99ffd4d53666dbfdc2ae0dfe
There is a problem with the processing of this commit.
When the api-server's GET http://xxx/metrics request is interrupted abnormally, session.DeleteAPIServerConnection must be called to block and wait for the ProxyTunnelMessageToApiserver function call to complete. Otherwise, ContainerMetricsConnection.writer will become a wild pointer, causing the above panic.
![image](https://github.com/kubeedge/kubeedge/assets/7654588/829401eb-1bff-4b53-ba6b-38e00a3d6d4c)
![image](https://github.com/kubeedge/kubeedge/assets/7654588/ed3f7fe7-375d-4b11-8210-78162133d667)
**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): cloudcore:v1.14.2
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by CKchen0726** [comment]
Similar but not identical issues

**Comment by CKchen0726** [comment]
Similar but not identical issues
```
E0514 14:55:17.800567       1 streamserver.go:177] Failed to get metrics, err: apiconnection Serve APIServer_MetricsConnection MessageID 31 in Tunnel session [star1-orin02] error APIServer_MetricsConnection MessageID 31 find edge peer done, so stop this connection
I0514 14:55:17.717687       1 log.go:245] http: panic serving 10.112.4.3:57498: Write called after Handler finished
goroutine 3787 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/golang/src/net/http/server.go:1873 +0xb0
panic({0x1a95ac0?, 0x24fed50?})
        /usr/lib/golang/src/runtime/panic.go:920 +0x26c
net/http.(*http2responseWriter).write(0xffff60c2f988?, 0xffffa7d1d100?, {0x4006bd5800?, 0x4000ff5000?, 0x4006b82c90?}, {0x0?, 0x4003e2d528?})
        /usr/lib/golang/src/net/http/h2_bundle.go:6836 +0x15c
net/http.(*http2responseWriter).Write(0x4003e2d538?, {0x4006bd5800?, 0x4003e2d648?, 0x1875ed4?})
        /usr/lib/golang/src/net/http/h2_bundle.go:6825 +0x38
github.com/kubeedge/kubeedge/cloud/pkg/cloudstream.(*ContainerMetricsConnection).WriteToAPIServer(0x1bcb960?, {0x4006bd5800?, 0x6?, 0x1?})
        /root/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudstream/containermetrics_connection.go:63 +0x2c
github.com/kubeedge/kubeedge/cloud/pkg/cloudstream.(*Session).ProxyTunnelMessageToApiserver(0x4005130180, 0x4006b82c90)
        /root/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudstream/session.go:102 +0x390
github.com/kubeedge/kubeedge/cloud/pkg/cloudstream.(*Session).Serve(0x4005130180)
        /root/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudstream/session.go:81 +0x98
github.com/kubeedge/kubeedge/cloud/pkg/cloudstream.(*TunnelServer).connect(0x4003ab4140, 0x400512a390, 0xffff60bb75c8?)
        /root/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudstream/tunnelserver.go:143 +0x588
github.com/kubeedge/kubeedge/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0x4003abe6c0, {0x2519f48, 0x40037c8540}, 0x4005142000)
        /root/go/src/github.com/kubeedge/kubeedge/vendor/github.com/emicklei/go-restful/container.go:294 +0x42c
net/http.HandlerFunc.ServeHTTP(0x4003e2dad8?, {0x2519f48?, 0x40037c8540?}, 0x10?)
        /usr/lib/golang/src/net/http/server.go:2141 +0x38
net/http.(*ServeMux).ServeHTTP(0x4003e2dac8?, {0x2519f48, 0x40037c8540}, 0x4005142000)
        /usr/lib/golang/src/net/http/server.go:2519 +0x144
github.com/kubeedge/kubeedge/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0x3b6a7e0?, {0x2519f48?, 0x40037c8540?}, 0x4003e2db40?)
        /root/go/src/github.com/kubeedge/kubeedge/vendor/github.com/emicklei/go-restful/container.go:311 +0x1bc
net/http.serverHandler.ServeHTTP({0x400512a210?}, {0x2519f48?, 0x40037c8540?}, 0x6?)
        /usr/lib/golang/src/net/http/server.go:2943 +0xbc
net/http.(*conn).serve(0x40048fe120, {0x2529528, 0x4001002b70})
        /usr/lib/golang/src/net/http/server.go:2014 +0x518
created by net/http.(*Server).Serve in goroutine 3104
        /usr/lib/golang/src/net/http/server.go:3091 +0x4cc
I0514 14:55:17.916019       1 containermetrics_connection.go:100] APIServer_MetricsConnection MessageID 34 end successful
I0514 14:55:17.916061       1 session.go:139] Delete a apiserver connection APIServer_MetricsConnection MessageID 34 from Tunnel session [star1-orin03]
I0514 14:55:17.916075       1 streamserver.go:214] Delete APIServer_MetricsConnection MessageID 34 from Tunnel session [star1-orin03]
E0514 14:55:17.916085       1 streamserver.go:177] Failed to get metrics, err: apiconnection Serve APIServer_MetricsConnection MessageID 34 in Tunnel session [star1-orin03] error APIServer_MetricsConnection MessageID 34 find edge peer done, so stop this connection
```
