### ISSUE TITLE
When enable dynamicController, cloudcore panic

### ISSUE THREAD

**Issue by xisanlou** [kubeedge/kubeedge#5010]
**What happened and what you expected to happen**:
I enable dynamicController:
#kubectl -n kubeedge edit configmap cloudcore
      dynamicController:
        enable: true
and restart cloudcore, cloudcore panic with error:
------------------
I0913 14:54:07.251436       1 downstream.go:957] Start downstream devicecontroller
I0913 14:54:07.258755       1 downstream.go:334] start downstream controller
W0913 14:54:07.450212       1 message_dispatcher.go:489] message pool for edge node k24e17 not found and created now
panic: interface conversion: interface {} is *v1alpha1.ObjectSync, not *v1alpha1.ClusterObjectSync

goroutine 401 [running]:
github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1.(*clusterObjectSyncLister).List.func1({0x1cf1580, 0xc000cf3fb8})
        /go/src/github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go:53 +0xc5
github.com/kubeedge/kubeedge/vendor/k8s.io/client-go/tools/cache.ListAll({0x2021aa8, 0xc0004bb338}, {0x201dd40, 0xc000dd1008}, 0xc000e09d88)
        /go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/client-go/tools/cache/listers.go:40 +0xa2
github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1.(*clusterObjectSyncLister).List(0x3199df8, {0x201dd40, 0xc000dd1008})
        /go/src/github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go:52 +0x7a
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).deleteClusterObjectSyncs(0xc0000fd880)
        /go/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:167 +0x62
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).Start(0xc0000fd880)
        /go/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:109 +0x76
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.moduleKeeper({0x1d39ca4, 0xe}, 0xc000695440, {{0x1d39ca4, 0xe}, {0x1d31dc5, 0x7}, {0x0, {0x0, 0x0}}})
        /go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:77 +0xcf
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.StartModules
        /go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:45 +0x4f7
---------------------
Note this:
panic: interface conversion: interface {} is *v1alpha1.ObjectSync, not *v1alpha1.ClusterObjectSync

A  api error?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.24.16
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.14.1

**Comment by xisanlou** [comment]
resolved by 
https://github.com/kubeedge/kubeedge/pull/4918

**Comment by xisanlou** [comment]
resolved by
https://github.com/kubeedge/kubeedge/pull/4918
