### ISSUE TITLE
Request Scope Creater Scheme Implementation

### ISSUE THREAD

**Issue by Windrow14** [kubeedge/kubeedge#5350]
**What would you like to be added/modified**:

`handlers.RequestScope` needs an implementation of its `Creater`.

**Why is this needed**:

After fixing the panic issue described in https://github.com/kubeedge/kubeedge/pull/5313 by adding `fakeTypeConverter` and `fakeFieldManager`, the panic still goes on. So this issue is also a bug report.

This time, panic happens at `Creater`. which is not defined.
```
		result, err := finisher.FinishRequest(ctx, func() (runtime.Object, error) {
			liveObj, err := scope.Creater.New(scope.Kind)
			if err != nil {
				return nil, fmt.Errorf("failed to create new object (Create for %v): %v", scope.Kind, err)
			}
			obj = scope.FieldManager.UpdateNoErrors(liveObj, obj, managerOrUserAgent(options.FieldManager, req.UserAgent()))
			admit = fieldmanager.NewManagedFieldsValidatingAdmissionController(admit)
			...
```

If we set `Creater` to `runtime.NewScheme()` in `func NewRequestScope() *handlers.RequestScope`, panic no longer happens, but CRD such as `Ciliumendpoint` cannot be created.
Following error appears:

Jan 08 16:42:54 edge121 edgecore[609218]: E0108 16:42:54.998857  609218 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s: "failed to create new object (Create for cilium.io/v2, Kind=Ciliumendpoint): no kind \"Ciliumendpoint\" is registered for version \"cilium.io/v2\" in scheme \"pkg/metamanager/metaserver/kubernetes/scope/scope.go:49\""}: failed to create new object (Create for cilium.io/v2, Kind=Ciliumendpoint):no kind "Ciliumendpoint" is registered for version "cilium.io/v2" in scheme "pkg/metamanager/metaserver/kubernetes/scope/scope.go:49"

So we need an implementation of this `Creater` which can really do creation.

**Comment by Shelley-BaoYue** [comment]
Does this issue occur with the KubeEdge master branch? Or there is also the same problem in v1.15?

**Comment by Windrow14** [comment]
> Does this issue occur with the KubeEdge master branch? Or there is also the same problem in v1.15?

It does occur on master branch. It is introduced after:
```
commit 7c02a3f52090618df852f3184297a91cd00b2d0a
Author: Shelley-BaoYue <baoyue2@huawei.com>
Date:   Mon Nov 20 10:57:11 2023 +0800

    update vendor for kubernetes v1.27.7
    
    Signed-off-by: Shelley-BaoYue <baoyue2@huawei.com>

diff --git a/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go b/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
index 78c1d2f52..120d3f665 100644
--- a/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
+++ b/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
@@ -191,14 +191,13 @@ func createHandler(r rest.NamedCreater, scope *RequestScope, admit admission.Int
                // Dedup owner references before updating managed fields
                dedupOwnerReferencesAndAddWarning(obj, req.Context(), false)
                result, err := finisher.FinishRequest(ctx, func() (runtime.Object, error) {
-                       if scope.FieldManager != nil {
-                               liveObj, err := scope.Creater.New(scope.Kind)
-                               if err != nil {
-                                       return nil, fmt.Errorf("failed to create new object (Create for %v): %v", scope.Kind, err)
-                               }
-                               obj = scope.FieldManager.UpdateNoErrors(liveObj, obj, managerOrUserAgent(options.FieldManager, req.UserAgent()))
-                               admit = fieldmanager.NewManagedFieldsValidatingAdmissionController(admit)
+                       liveObj, err := scope.Creater.New(scope.Kind)
+                       if err != nil {
+                               return nil, fmt.Errorf("failed to create new object (Create for %v): %v", scope.Kind, err)
                        }
+                       obj = scope.FieldManager.UpdateNoErrors(liveObj, obj, managerOrUserAgent(options.FieldManager, req.UserAgent()))
+                       admit = fieldmanager.NewManagedFieldsValidatingAdmissionController(admit)
+
                        if mutatingAdmission, ok := admit.(admission.MutationInterface); ok && mutatingAdmission.Handles(admission.Create) {
                                if err := mutatingAdmission.Admit(ctx, admissionAttributes, scope); err != nil {
                                        return nil, err
```
These lines used to be in `if` statement, and the condition never met. After synchronization with k8s 1.27.7, `if` is removed, nil `scope.Creater` panics.

**Comment by ZhengXinwei-F** [comment]
```
type unstructuredCreator struct{}

func (c unstructuredCreator) New(kind schema.GroupVersionKind) (runtime.Object, error) {
    ret := &unstructured.Unstructured{}
    ret.SetGroupVersionKind(kind)
    return ret, nil
}
```

```
Creater: unstructuredCreator{},
```

You could try using unstructuredCreator to finish the work first. Later, we may need to differentiate between k8s standard resources, kubeedge crds, and other crds, as well as obtain different schemes for different resource types.

Like:
```
	schemeMap := map[string]runtime.ObjectCreater{
		"kubernetes-resource": edgescheme.Scheme,
		"kube-edge-crd":       edgescheme.Scheme,
		"other-crd":           unstructuredCreator{},
	}
```

**Comment by Windrow14** [comment]
wackxu added these lines 14 months ago, is `kubeEdgeScheme` related to here?
```
var (
	// kubeScheme is built-in resources scheme for converting group,
	// version, and kind information to and from Go schemas
	kubeScheme = scheme.Scheme

	// kubeEdgeScheme is KubeEdge CRD resources scheme for converting
	// group, version, and kind information to and from Go schemas
	kubeEdgeScheme = edgescheme.Scheme
)
```

**Comment by ZhengXinwei-F** [comment]
I apologize for the mistake. This is accurate.
```
schemeMap := map[string]runtime.ObjectCreater{
	"kubernetes-resource": scheme.Scheme,
	"kube-edge-crd":       edgescheme.Scheme,
	"other-crd":           unstructuredCreator{},
}
```

Here, wackxu only has kubeedge crds schemes and kubernetes resources schemes . This issue necessitates an unknown crd creator.

**Comment by Windrow14** [comment]
Thank you for the suggestion! This work-around works for my current scenario.

```
diff --git a/edge/pkg/metamanager/metaserver/kubernetes/scope/scope.go b/edge/pkg/metamanager/metaserver/kubernetes/scope/scope.go
index 4da87f299..cb24b01cb 100644
--- a/edge/pkg/metamanager/metaserver/kubernetes/scope/scope.go
+++ b/edge/pkg/metamanager/metaserver/kubernetes/scope/scope.go
@@ -4,6 +4,7 @@ import (
        "k8s.io/apiextensions-apiserver/pkg/crdserverscheme"
        "k8s.io/apimachinery/pkg/api/meta"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+       "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
        "k8s.io/apimachinery/pkg/runtime"
        "k8s.io/apimachinery/pkg/runtime/schema"
        "k8s.io/apimachinery/pkg/util/managedfields"
@@ -17,6 +18,14 @@ import (
        "github.com/kubeedge/kubeedge/edge/pkg/metamanager/metaserver/kubernetes/serializer"
 )
 
+type unstructuredCreator struct{}
+
+func (c unstructuredCreator) New(kind schema.GroupVersionKind) (runtime.Object, error) {
+       ret := &unstructured.Unstructured{}
+       ret.SetGroupVersionKind(kind)
+       return ret, nil
+}
+
 func NewRequestScope() *handlers.RequestScope {
        fakeTypeConverter, err := managedfields.NewTypeConverter(make(map[string]*spec.Schema), false)
        if err != nil {
@@ -46,7 +55,7 @@ func NewRequestScope() *handlers.RequestScope {
 
                Serializer:     serializer.NewNegotiatedSerializer(),
                ParameterCodec: scheme.ParameterCodec,
-               //Creater:         nil,
+               Creater:         unstructuredCreator{},
                Convertor: fakers.NewFakeObjectConvertor(),
                Defaulter: fakers.NewFakeObjectDefaulter(),
                Typer:     crdserverscheme.NewUnstructuredObjectTyper(),
```

**Comment by Windrow14** [comment]
> Thank you for the suggestion! This work-around works for my current scenario.

Sorry, no. Still panics on creation...

**Comment by ZhengXinwei-F** [comment]
> > Thank you for the suggestion! This work-around works for my current scenario.
> 
> Sorry, no. Still panics on creation...

Is there a possibility of success? What is the new place for error reporting?

**Comment by Windrow14** [comment]
```
Jan 10 11:29:37 edge121 edgecore[692757]: E0110 11:29:37.108929  692757 wrap.go:58] "apiserver panic'd" method="POST" URI="/apis/cilium.io/v2/namespaces/default/ciliumendpoints" auditID=""
Jan 10 11:29:37 edge121 edgecore[692757]: I0110 11:29:37.109156  692757 log.go:194] http: panic serving 127.0.0.1:59652: runtime error: invalid memory address or nil pointer dereference
Jan 10 11:29:37 edge121 edgecore[692757]: goroutine 7008 [running]:
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1.1()
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher.go:105 +0xa5
Jan 10 11:29:37 edge121 edgecore[692757]: panic({0x2a59b60, 0x4b01680})
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/runtime/panic.go:884 +0x213
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*structuredMergeManager).toVersioned(...)
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/structuredmerge.go:181
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*structuredMergeManager).Update(0xc001da2bd0, {0x3364660, 0xc000f32b30}, {0x3364660, 0xc000f32b18}, {0x7f8a21e86f80, 0xc00187f8b0}, {0x2ee9392, 0x11})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/structuredmerge.go:90 +0x9f
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*stripMetaManager).Update(0xc0018fe570, {0x3364660?, 0xc000f32b30?}, {0x3364660?, 0xc000f32b18?}, {0x7f8a21e86f80?, 0xc00187f8b0?}, {0x2ee9392, 0x11})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/stripmeta.go:58 +0x6d
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*managedFieldsUpdater).Update(0x2?, {0x3364660?, 0xc000f32b30?}, {0x3364660?, 0xc000f32b18?}, {0x7f8a21e86f80?, 0xc00187f8b0?}, {0xc000738f60, 0x2f})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/managedfieldsupdater.go:47 +0x83
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*buildManagerInfoManager).Update(0xc001ce8b80, {0x3364660, 0xc000f32b30}, {0x3364660, 0xc000f32b18}, {0x7f8a21e86f80, 0xc00187f8b0}, {0xc001a51930?, 0x2eadd00?})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/buildmanagerinfo.go:51 +0x103
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*capManagersManager).Update(0xc0017556b0, {0x3364660?, 0xc000f32b30?}, {0x3364660?, 0xc000f32b18?}, {0x7f8a21e86f80?, 0xc00187f8b0?}, {0xc001a51930?, 0xc001d7fc90?})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/capmanagers.go:48 +0x65
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*skipNonAppliedManager).Update(0xc00057e380, {0x3364660?, 0xc000f32b30}, {0x3364660, 0xc000f32b18}, {0x7f8a21e86f80, 0xc00187f8b0?}, {0xc001a51930, 0xc})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/skipnonapplied.go:75 +0x14b
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*lastAppliedManager).Update(0xc001d7fd40?, {0x3364660?, 0xc000f32b30?}, {0x3364660?, 0xc000f32b18?}, {0x7f8a21e86f80?, 0xc00187f8b0?}, {0xc001a51930?, 0x3364958?})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/lastappliedmanager.go:53 +0x4d
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*lastAppliedUpdater).Update(0x3364660?, {0x3364660?, 0xc000f32b30?}, {0x3364660?, 0xc000f32b18?}, {0x7f8a21e86f80?, 0xc00187f8b0?}, {0xc001a51930?, 0x0?})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/lastappliedupdater.go:43 +0x4d
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*FieldManager).Update(0xc000125f40, {0x3364660, 0xc000f32b30}, {0x3364660, 0xc000f32b18}, {0xc001a51930, 0xc})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/fieldmanager.go:128 +0xe5
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/managedfields/internal.(*FieldManager).UpdateNoErrors(0xc0010ab560?, {0x3364660?, 0xc000f32b30?}, {0x3364660, 0xc000f32b18}, {0xc001a51930?, 0xe?})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/fieldmanager.go:143 +0x45
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.2()
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go:198 +0x273
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1()
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher.go:117 +0x8f
Jan 10 11:29:37 edge121 edgecore[692757]: created by k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher.go:92 +0xde
Jan 10 11:29:37 edge121 edgecore[692757]: goroutine 7018 [running]:
Jan 10 11:29:37 edge121 edgecore[692757]: net/http.(*conn).serve.func1()
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/net/http/server.go:1854 +0xbf
Jan 10 11:29:37 edge121 edgecore[692757]: panic({0x290f920, 0xc00187f8c0})
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/runtime/panic.go:890 +0x263
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0xc001392578, 0x1, 0x1b9c62b?})
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
Jan 10 11:29:37 edge121 edgecore[692757]: panic({0x290f920, 0xc00187f8c0})
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/runtime/panic.go:884 +0x213
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/endpoints/handlers/finisher.(*result).Return(0xc001392780?)
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher.go:53 +0xbc
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest({0x3382b48, 0xc00153a0f0}, 0xc0017cd560, 0x45d964b800, 0x306a320)
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher.go:126 +0x376
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/endpoints/handlers/finisher.FinishRequest(...)
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher.go:84
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1({0x3380d80, 0xc0018ba2a0}, 0xc00136ad00)
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go:193 +0x217a
Jan 10 11:29:37 edge121 edgecore[692757]: net/http.HandlerFunc.ServeHTTP(0xc000d0c4c0?, {0x3380d80?, 0xc0018ba2a0?}, 0xc00159c203?)
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/net/http/server.go:2122 +0x2f
Jan 10 11:29:37 edge121 edgecore[692757]: github.com/kubeedge/kubeedge/edge/pkg/metamanager/metaserver.(*MetaServer).BuildBasicHandler.func1({0x3380d80, 0xc0018ba2a0}, 0xc00136ad00)
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/edge/pkg/metamanager/metaserver/server.go:231 +0x1a2
Jan 10 11:29:37 edge121 edgecore[692757]: net/http.HandlerFunc.ServeHTTP(0xc001755440?, {0x3380d80?, 0xc0018ba2a0?}, 0xc001393948?)
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/net/http/server.go:2122 +0x2f
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/server/filters.withWaitGroup.func1({0x3380d80, 0xc0018ba2a0}, 0xc00136ad00)
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:86 +0x1e9
Jan 10 11:29:37 edge121 edgecore[692757]: net/http.HandlerFunc.ServeHTTP(0x3382aa0?, {0x3380d80?, 0xc0018ba2a0?}, 0x334d5a8?)
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/net/http/server.go:2122 +0x2f
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1({0x3380d80, 0xc0018ba2a0}, 0xc00136aa00)
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x1ed
Jan 10 11:29:37 edge121 edgecore[692757]: net/http.HandlerFunc.ServeHTTP(0x41e9b0?, {0x3380d80?, 0xc0018ba2a0?}, 0x0?)
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/net/http/server.go:2122 +0x2f
Jan 10 11:29:37 edge121 edgecore[692757]: k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1({0x3380d80?, 0xc0018ba2a0?}, 0xc001393ad0?)
Jan 10 11:29:37 edge121 edgecore[692757]:         /home/windrow/push/kubeedge/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:74 +0xb1
Jan 10 11:29:37 edge121 edgecore[692757]: net/http.HandlerFunc.ServeHTTP(0x0?, {0x3380d80?, 0xc0018ba2a0?}, 0x827454?)
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/net/http/server.go:2122 +0x2f
Jan 10 11:29:37 edge121 edgecore[692757]: net/http.serverHandler.ServeHTTP({0x3369598?}, {0x3380d80, 0xc0018ba2a0}, 0xc00136aa00)
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/net/http/server.go:2936 +0x316
Jan 10 11:29:37 edge121 edgecore[692757]: net/http.(*conn).serve(0xc000d37320, {0x3382b48, 0xc0005fea20})
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/net/http/server.go:1995 +0x612
Jan 10 11:29:37 edge121 edgecore[692757]: created by net/http.(*Server).Serve
Jan 10 11:29:37 edge121 edgecore[692757]:         /usr/local/go/src/net/http/server.go:3089 +0x5ed
```

**Comment by Windrow14** [comment]
Seems `Creater` is fine, panic at `FieldManager` this time.

**Comment by Windrow14** [comment]
Verification: 
1. Delete a `busybox` `DaemonSet`.
Cluster status:
```
windrow@windrow-PC:~$ kubectl get pod
NAME            READY   STATUS        RESTARTS   AGE
busybox-dt6w2   1/1     Terminating   0          9m15s
busybox-lkks4   1/1     Terminating   0          9m15s
windrow@windrow-PC:~$ kubectl get ciliumendpoint
NAME            SECURITY IDENTITY   ENDPOINT STATE   IPV4         IPV6
busybox-dt6w2   63465               ready            10.0.0.10    
busybox-lkks4   63465               ready            10.0.1.222   
windrow@windrow-PC:~$ kubectl get pod
No resources found in default namespace.
windrow@windrow-PC:~$ kubectl get ciliumendpoint
No resources found in default namespace.
```

2. Deploy a `busybox` `DaemonSet`.
```
windrow@windrow-PC:~$ kubectl get ciliumendpoint 
NAME            SECURITY IDENTITY   ENDPOINT STATE   IPV4         IPV6
busybox-459jl   63465               ready            10.0.0.110   
busybox-49dh9   63465               ready            10.0.1.22 
windrow@windrow-PC:~$ kubectl get pod
NAME            READY   STATUS    RESTARTS   AGE
busybox-459jl   1/1     Running   0          1m5s
busybox-49dh9   1/1     Running   0          1m5s
```

Edgecore logs:

Delete `DaemonSet`:
```
Jan 15 13:47:18 edge121 edgecore[704331]: E0115 13:47:18.939230  704331 agent.go:210] failed to process watch apps: map[]
Jan 15 13:47:18 edge121 edgecore[704331]: I0115 13:47:18.939335  704331 storage.go:212] [metaserver/reststorage] successfully apply for a watch listener (/api/v1/nodes) through cloud
Jan 15 13:47:18 edge121 edgecore[704331]: W0115 13:47:18.939360  704331 watcher.go:93] base storage now only support rev == 0, but get rev == 1176803, force set to 0!
Jan 15 13:47:18 edge121 edgecore[704331]: I0115 13:47:18.939410  704331 watcher.go:230] start watching, rev:0
Jan 15 13:47:18 edge121 edgecore[704331]: I0115 13:47:18.939415  704331 imitator.go:176] /v1, Resource=nodes,,pc-windrow-192-168-0-151
Jan 15 13:47:18 edge121 edgecore[704331]: I0115 13:47:18.939733  704331 watcher.go:200] get storage revision:1176994
Jan 15 13:47:44 edge121 edgecore[704331]: E0115 13:47:44.136474  704331 edged.go:286] resType is not pod or configmap or secret or volume: resType is ciliumendpoint
Jan 15 13:47:45 edge121 edgecore[704331]: I0115 13:47:45.108430  704331 scope.go:115] "RemoveContainer" containerID="ecafde6b9fb43809df8164a6cd1bebd1cb1c864789dbbbbff68c99c032490cdd"
Jan 15 13:47:45 edge121 edgecore[704331]: I0115 13:47:45.702691  704331 storage.go:267] [metaserver/reststorage] successfully delete (/cilium.io/v2/ciliumendpoints/default/busybox-lkks4) through cloud
Jan 15 13:47:46 edge121 edgecore[704331]: E0115 13:47:46.024609  704331 edged.go:286] resType is not pod or configmap or secret or volume: resType is ciliumendpoint
Jan 15 13:47:46 edge121 edgecore[704331]: I0115 13:47:46.110656  704331 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="97f378a78f087053071be727b3cc3402a376ec2eb10291a8d296328fb5ea326e"
Jan 15 13:47:46 edge121 edgecore[704331]: I0115 13:47:46.284091  704331 reconciler_common.go:172] "operationExecutor.UnmountVolume started for volume \"kube-api-access-vpmm9\" (UniqueName: \"kubernetes.io/projected/fe667df6-49e8-4b08-8c27-d83339b070c7-kube-api-access-vpmm9\") pod \"fe667df6-49e8-4b08-8c27-d83339b070c7\" (UID: \"fe667df6-49e8-4b08-8c27-d83339b070c7\") "
Jan 15 13:47:47 edge121 edgecore[704331]: I0115 13:47:47.854801  704331 operation_generator.go:882] UnmountVolume.TearDown succeeded for volume "kubernetes.io/projected/fe667df6-49e8-4b08-8c27-d83339b070c7-kube-api-access-vpmm9" (OuterVolumeSpecName: "kube-api-access-vpmm9") pod "fe667df6-49e8-4b08-8c27-d83339b070c7" (UID: "fe667df6-49e8-4b08-8c27-d83339b070c7"). InnerVolumeSpecName "kube-api-access-vpmm9". PluginName "kubernetes.io/projected", VolumeGidValue ""
Jan 15 13:47:47 edge121 edgecore[704331]: I0115 13:47:47.894058  704331 reconciler_common.go:300] "Volume detached for volume \"kube-api-access-vpmm9\" (UniqueName: \"kubernetes.io/projected/fe667df6-49e8-4b08-8c27-d83339b070c7-kube-api-access-vpmm9\") on node \"pc-windrow-192-168-0-151\" DevicePath \"\""
Jan 15 13:47:48 edge121 edgecore[704331]: E0115 13:47:48.169613  704331 imitator.go:266] failed to unmarshal message content to unstructured obj: Object 'Kind' is missing in '{"gracePeriodSeconds":0,"preconditions":{"uid":"fe667df6-49e8-4b08-8c27-d83339b070c7"}}'
Jan 15 13:47:50 edge121 edgecore[704331]: I0115 13:47:50.212348  704331 kubelet_volumes.go:161] "Cleaned up orphaned pod volumes dir" podUID="fe667df6-49e8-4b08-8c27-d83339b070c7" path="/var/lib/edged/pods/fe667df6-49e8-4b08-8c27-d83339b070c7/volumes"
```

Deploy `DaemonSet`:
```
Jan 15 13:48:01 edge121 edgecore[704331]: I0115 13:48:01.062660  704331 topology_manager.go:212] "Topology Admit Handler" podUID="3ab60880-12dc-4f13-823e-82679491d9db" podNamespace="default" podName="busybox-49dh9"
Jan 15 13:48:01 edge121 edgecore[704331]: E0115 13:48:01.062715  704331 cpu_manager.go:395] "RemoveStaleState: removing container" podUID="fe667df6-49e8-4b08-8c27-d83339b070c7" containerName="busybox"
...
Jan 15 13:48:01 edge121 edgecore[704331]: I0115 13:48:01.063063  704331 memory_manager.go:346] "RemoveStaleState removing state" podUID="fe667df6-49e8-4b08-8c27-d83339b070c7" containerName="busybox"
Jan 15 13:48:01 edge121 edgecore[704331]: I0115 13:48:01.063068  704331 memory_manager.go:346] "RemoveStaleState removing state" podUID="54194f09-2cde-452a-a438-d7a0016a55de" containerName="iperf-client"
Jan 15 13:48:01 edge121 edgecore[704331]: I0115 13:48:01.063072  704331 memory_manager.go:346] "RemoveStaleState removing state" podUID="fe667df6-49e8-4b08-8c27-d83339b070c7" containerName="busybox"
Jan 15 13:48:01 edge121 edgecore[704331]: E0115 13:48:01.455417  704331 edged.go:286] resType is not pod or configmap or secret or volume: resType is ciliumendpoint
Jan 15 13:48:01 edge121 edgecore[704331]: I0115 13:48:01.763222  704331 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-ddm4h\" (UniqueName: \"kubernetes.io/projected/3ab60880-12dc-4f13-823e-82679491d9db-kube-api-access-ddm4h\") pod \"busybox-49dh9\" (UID: \"3ab60880-12dc-4f13-823e-82679491d9db\") " pod="default/busybox-49dh9"
Jan 15 13:48:02 edge121 edgecore[704331]: E0115 13:48:02.150503  704331 serviceaccount.go:112] query meta "default"/"default"/[]string(nil)/3607/v1.BoundObjectReference{Kind:"Pod", APIVersion:"v1", Name:"busybox-49dh9", UID:"3ab60880-12dc-4f13-823e-82679491d9db"} length error
Jan 15 13:48:03 edge121 edgecore[704331]: E0115 13:48:03.528367  704331 storage.go:92] [metaserver/reststorage] failed to get obj from cloud: ciliumendpoints.cilium.io "busybox-49dh9" not found
Jan 15 13:48:03 edge121 edgecore[704331]: E0115 13:48:03.528927  704331 store.go:62] the server could not find the requested resource
Jan 15 13:48:03 edge121 edgecore[704331]: E0115 13:48:03.529388  704331 fieldmanager.go:152] "[SHOULD NOT HAPPEN] failed to update managedFields" err="failed to convert new object (default/busybox-49dh9; cilium.io/v2, Kind=CiliumEndpoint) to smd typed: no corresponding type for cilium.io/v2, Kind=CiliumEndpoint" versionKind="cilium.io/v2, Kind=CiliumEndpoint" namespace="default" name="busybox-49dh9"
Jan 15 13:48:03 edge121 edgecore[704331]: I0115 13:48:03.540950  704331 storage.go:250] [metaserver/reststorage] successfully create (/cilium.io/v2/ciliumendpoints/default/busybox-49dh9)
Jan 15 13:48:03 edge121 edgecore[704331]: E0115 13:48:03.914270  704331 edged.go:286] resType is not pod or configmap or secret or volume: resType is ciliumendpoint
```

**Comment by ZhengXinwei-F** [comment]
This solution appears to be workable. However, we could implement some E2E tests for MetaServer to prevent this type issue from recurring.
@Windrow14 Do you want to work on this enhancement feature?

**Comment by Windrow14** [comment]
> This solution appears to be workable. However, we could implement some E2E tests for MetaServer to prevent this type issue from recurring. @Windrow14 Do you want to work on this enhancement feature?

Yes, but later maybe. For now, I think the fix to panic should better be merged as soon as possible.

**Comment by fujitatomoya** [comment]
@ZhengXinwei-F could you point out the reference for `e2e test for metaserver` if that is already available?
CC: @Windrow14
