### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CKchen0726** [kubeedge/kubeedge#5457]
**What happened**:
I0307 16:16:14.095926   34662 scope.go:115] "RemoveContainer" containerID="2c0ece0cb7ccec1e2bac704fc69ba1f95491a66b0382d031698569327ab1564f"
E0307 16:16:14.096088   34662 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"nginx-3\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=nginx-3 pod=nginx-3-satellite2-6779cd8454-rvd6f_default(b7b45c54-de34-4ffc-a345-40b04406731d)\"" pod="default/nginx-3-satellite2-6779cd8454-rvd6f" podUID="b7b45c54-de34-4ffc-a345-40b04406731d"
E0307 16:16:14.230142   34662 token_manager.go:180] "Expiration seconds was nil for token request" tokenRequest="&TokenRequest{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:TokenRequestSpec{Audiences:[],BoundObjectRef:nil,ExpirationSeconds:nil,},Status:TokenRequestStatus{Token:,ExpirationTimestamp:0001-01-01 00:00:00 +0000 UTC,},}"
I0307 16:16:19.730449   34662 reconciler_common.go:172] "operationExecutor.UnmountVolume started for volume \"kube-api-access-ncld9\" (UniqueName: \"kubernetes.io/projected/381468fc-8995-46c4-8ba8-5fc75cc97f09-kube-api-access-ncld9\") pod \"381468fc-8995-46c4-8ba8-5fc75cc97f09\" (UID: \"381468fc-8995-46c4-8ba8-5fc75cc97f09\") "
W0307 16:16:19.730535   34662 empty_dir.go:499] Warning: Unmount skipped because path does not exist: /var/lib/edged/pods/381468fc-8995-46c4-8ba8-5fc75cc97f09/volumes/kubernetes.io~projected/kube-api-access-ncld9
E0307 16:16:19.730704   34662 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/projected/381468fc-8995-46c4-8ba8-5fc75cc97f09-kube-api-access-ncld9 podName:381468fc-8995-46c4-8ba8-5fc75cc97f09 nodeName:}" failed. No retries permitted until 2024-03-07 16:17:23.730651397 +0800 CST m=+1130.748624772 (durationBeforeRetry 1m4s). Error: recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 3324 [running]:
k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc000f35e78)
        /root/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:162 +0x6b
panic({0x2a8dba0, 0x4d8c3d0})
        /usr/local/go/src/runtime/panic.go:890 +0x263
k8s.io/kubernetes/pkg/kubelet/token.(*Manager).DeleteServiceAccountToken(0xc00062c300, {0xc001142960, 0x24})
        /root/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/token/token_manager.go:140 +0xf1
k8s.io/kubernetes/pkg/volume/projected.(*projectedVolumeUnmounter).TearDownAt(0xc000974858, {0xc000fb4ee0, 0x6e})
        /root/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/volume/projected/projected.go:382 +0x282
k8s.io/kubernetes/pkg/volume/projected.(*projectedVolumeUnmounter).TearDown(0xc000974858)
        /root/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/volume/projected/projected.go:368 +0x4e
k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateUnmountVolumeFunc.func1()
        /root/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go:859 +0x193
k8s.io/kubernetes/pkg/volume/util/types.(*GeneratedOperations).Run(0xc001423950)
        /root/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go:79 +0x1c2
k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1()
        /root/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:190 +0xf4
created by k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run
        /root/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:185 +0x8aa

**What you expected to happen**:
No panic

**How to reproduce it (as minimally and precisely as possible)**:
When the edge node was online, an Nginx application was deployed and functioning properly. Later, the edge node experienced an offline period, and eventually, upon returning to an online state, kubelet tried to update the pod's status but encountered an error stating 'pod not found,' subsequently leading to a panic

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): v1.26.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): KubeEdge release-1.16
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`): Architecture:          x86_64; CPU op-mode(s):        32-bit, 64-bit; Byte Order:            Little Endian; CPU(s):                32
  - OS (e.g. `cat /etc/os-release`): CentOS Linux 7 (Core)
  - Kernel (e.g. `uname -a`): Linux edgenode-3 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  - Go version (e.g. `go version`): go version go1.20 linux/amd64
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Shelley-BaoYue** [comment]
Sorry I failed to reproduce this issue in my environment.  Could you please provide mode details about reproduce steps? Is the  pod scheduled to other nodes? and if there any residual data in edge database?
